if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


;(function(){
var f,aa=this;function ba(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function fa(a,b){null!=a&&this.append.apply(this,arguments)}f=fa.prototype;f.Ka="";f.set=function(a){this.Ka=""+a};f.append=function(a,b,c){this.Ka+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.Ka+=arguments[d];return this};f.clear=function(){this.Ka=""};f.toString=function(){return this.Ka};function ga(a,b){a.sort(b||ha)}function ka(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||ha;ga(a,function(a,b){return d(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value}function ha(a,b){return a>b?1:a<b?-1:0};var la;if("undefined"===typeof ma)var ma=function(){throw Error("No *print-fn* fn set for evaluation environment");};if("undefined"===typeof oa)var oa=function(){throw Error("No *print-err-fn* fn set for evaluation environment");};var pa=null;if("undefined"===typeof ra)var ra=null;function ta(){return new ua(null,5,[va,!0,wa,!0,ya,!1,za,!1,Aa,null],null)}function t(a){return null!=a&&!1!==a}function Ba(a){return a instanceof Array}function Ca(a){return null==a?!0:!1===a?!0:!1}
function u(a,b){return a[n(null==b?null:b)]?!0:a._?!0:!1}function Ea(a){return null==a?null:a.constructor}function x(a,b){var c=Ea(b),c=t(t(c)?c.vb:c)?c.fb:n(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function Fa(a){var b=a.fb;return t(b)?b:""+B(a)}var Ga="undefined"!==typeof Symbol&&"function"===n(Symbol)?Symbol.iterator:"@@iterator";function Ha(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
function Ia(a){function b(a,b){a.push(b);return a}var c=[];return Ka?Ka(b,c,a):La.call(null,b,c,a)}function Ma(){}
var Na=function Na(b){if(null!=b&&null!=b.X)return b.X(b);var c=Na[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Na._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("ICounted.-count",b);},Oa=function Oa(b){if(null!=b&&null!=b.R)return b.R(b);var c=Oa[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Oa._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IEmptyableCollection.-empty",b);};function Pa(){}
var Qa=function Qa(b,c){if(null!=b&&null!=b.N)return b.N(b,c);var d=Qa[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=Qa._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("ICollection.-conj",b);};function Ra(){}
var D=function D(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return D.a(arguments[0],arguments[1]);case 3:return D.g(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(c.length)].join(""));}};
D.a=function(a,b){if(null!=a&&null!=a.K)return a.K(a,b);var c=D[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=D._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw x("IIndexed.-nth",a);};D.g=function(a,b,c){if(null!=a&&null!=a.ga)return a.ga(a,b,c);var d=D[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=D._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw x("IIndexed.-nth",a);};D.G=3;function Ta(){}
var E=function E(b){if(null!=b&&null!=b.W)return b.W(b);var c=E[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=E._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("ISeq.-first",b);},F=function F(b){if(null!=b&&null!=b.ca)return b.ca(b);var c=F[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=F._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("ISeq.-rest",b);};function Ua(){}function Va(){}
var Wa=function Wa(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return Wa.a(arguments[0],arguments[1]);case 3:return Wa.g(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(c.length)].join(""));}};
Wa.a=function(a,b){if(null!=a&&null!=a.T)return a.T(a,b);var c=Wa[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=Wa._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw x("ILookup.-lookup",a);};Wa.g=function(a,b,c){if(null!=a&&null!=a.H)return a.H(a,b,c);var d=Wa[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=Wa._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw x("ILookup.-lookup",a);};Wa.G=3;
var Xa=function Xa(b,c,d){if(null!=b&&null!=b.Ta)return b.Ta(b,c,d);var e=Xa[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Xa._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw x("IAssociative.-assoc",b);};function Ya(){}function $a(){}
var ab=function ab(b){if(null!=b&&null!=b.lb)return b.lb();var c=ab[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=ab._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IMapEntry.-key",b);},bb=function bb(b){if(null!=b&&null!=b.mb)return b.mb();var c=bb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=bb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IMapEntry.-val",b);};function cb(){}
var db=function db(b,c,d){if(null!=b&&null!=b.nb)return b.nb(b,c,d);var e=db[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=db._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw x("IVector.-assoc-n",b);},eb=function eb(b){if(null!=b&&null!=b.zb)return b.state;var c=eb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=eb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IDeref.-deref",b);};function fb(){}
var gb=function gb(b){if(null!=b&&null!=b.I)return b.I(b);var c=gb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=gb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IMeta.-meta",b);},ib=function ib(b,c){if(null!=b&&null!=b.L)return b.L(b,c);var d=ib[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=ib._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("IWithMeta.-with-meta",b);};function jb(){}
var kb=function kb(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 2:return kb.a(arguments[0],arguments[1]);case 3:return kb.g(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(c.length)].join(""));}};
kb.a=function(a,b){if(null!=a&&null!=a.U)return a.U(a,b);var c=kb[n(null==a?null:a)];if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);c=kb._;if(null!=c)return c.a?c.a(a,b):c.call(null,a,b);throw x("IReduce.-reduce",a);};kb.g=function(a,b,c){if(null!=a&&null!=a.V)return a.V(a,b,c);var d=kb[n(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=kb._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw x("IReduce.-reduce",a);};kb.G=3;
var lb=function lb(b,c){if(null!=b&&null!=b.m)return b.m(b,c);var d=lb[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=lb._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("IEquiv.-equiv",b);},mb=function mb(b){if(null!=b&&null!=b.F)return b.F(b);var c=mb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=mb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IHash.-hash",b);};function nb(){}
var ob=function ob(b){if(null!=b&&null!=b.P)return b.P(b);var c=ob[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=ob._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("ISeqable.-seq",b);};function pb(){}function qb(){}function rb(){}
var sb=function sb(b){if(null!=b&&null!=b.bb)return b.bb(b);var c=sb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=sb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IReversible.-rseq",b);},G=function G(b,c){if(null!=b&&null!=b.tb)return b.tb(0,c);var d=G[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=G._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("IWriter.-write",b);},vb=function vb(b,c,d){if(null!=b&&null!=b.D)return b.D(b,c,d);var e=
vb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=vb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw x("IPrintWithWriter.-pr-writer",b);},wb=function wb(b,c,d){if(null!=b&&null!=b.sb)return b.sb(0,c,d);var e=wb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=wb._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw x("IWatchable.-notify-watches",b);},xb=function xb(b){if(null!=b&&null!=b.Va)return b.Va(b);var c=xb[n(null==b?null:
b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=xb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IEditableCollection.-as-transient",b);},yb=function yb(b,c){if(null!=b&&null!=b.cb)return b.cb(b,c);var d=yb[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=yb._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("ITransientCollection.-conj!",b);},zb=function zb(b){if(null!=b&&null!=b.eb)return b.eb(b);var c=zb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,
b);c=zb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("ITransientCollection.-persistent!",b);},Ab=function Ab(b,c,d){if(null!=b&&null!=b.Wa)return b.Wa(b,c,d);var e=Ab[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Ab._;if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw x("ITransientAssociative.-assoc!",b);},Bb=function Bb(b,c,d){if(null!=b&&null!=b.rb)return b.rb(0,c,d);var e=Bb[n(null==b?null:b)];if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);e=Bb._;
if(null!=e)return e.g?e.g(b,c,d):e.call(null,b,c,d);throw x("ITransientVector.-assoc-n!",b);};function Cb(){}
var Db=function Db(b,c){if(null!=b&&null!=b.Qa)return b.Qa(b,c);var d=Db[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=Db._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("IComparable.-compare",b);},Eb=function Eb(b){if(null!=b&&null!=b.pb)return b.pb();var c=Eb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Eb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IChunk.-drop-first",b);},Fb=function Fb(b){if(null!=b&&null!=b.jb)return b.jb(b);var c=
Fb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Fb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IChunkedSeq.-chunked-first",b);},Gb=function Gb(b){if(null!=b&&null!=b.kb)return b.kb(b);var c=Gb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Gb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IChunkedSeq.-chunked-rest",b);},Hb=function Hb(b){if(null!=b&&null!=b.ib)return b.ib(b);var c=Hb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,
b);c=Hb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IChunkedNext.-chunked-next",b);},Ib=function Ib(b,c){if(null!=b&&null!=b.Kb)return b.Kb(b,c);var d=Ib[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=Ib._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("IReset.-reset!",b);},Kb=function Kb(b){if(null!=b&&null!=b.Ha)return b.Ha(b);var c=Kb[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Kb._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IIterable.-iterator",
b);};function Lb(a){this.Pb=a;this.h=1073741824;this.v=0}Lb.prototype.tb=function(a,b){return this.Pb.append(b)};function Mb(a){var b=new fa;a.D(null,new Lb(b),ta());return""+B(b)}var Nb="undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function Ob(a){a=Nb(a|0,-862048943);return Nb(a<<15|a>>>-15,461845907)}
function Pb(a,b){var c=(a|0)^(b|0);return Nb(c<<13|c>>>-13,5)+-430675100|0}function Qb(a,b){var c=(a|0)^b,c=Nb(c^c>>>16,-2048144789),c=Nb(c^c>>>13,-1028477387);return c^c>>>16}function Rb(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=Pb(c,Ob(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^Ob(a.charCodeAt(a.length-1)):b;return Qb(b,Nb(2,a.length))}var Sb={},Tb=0;
function Vb(a){255<Tb&&(Sb={},Tb=0);var b=Sb[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)var e=c+1,d=Nb(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}else b=0;else b=0;Sb[a]=b;Tb+=1}return a=b}function Wb(a){null!=a&&(a.h&4194304||a.Vb)?a=a.F(null):"number"===typeof a?a=Math.floor(a)%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Vb(a),0!==a&&(a=Ob(a),a=Pb(0,a),a=Qb(a,4))):a=a instanceof Date?a.valueOf():null==a?0:mb(a);return a}
function Xb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Yb(a,b){if(a.oa===b.oa)return 0;var c=Ca(a.Y);if(t(c?b.Y:c))return-1;if(t(a.Y)){if(Ca(b.Y))return 1;c=ha(a.Y,b.Y);return 0===c?ha(a.name,b.name):c}return ha(a.name,b.name)}function Zb(a,b,c,d,e){this.Y=a;this.name=b;this.oa=c;this.Pa=d;this.$=e;this.h=2154168321;this.v=4096}f=Zb.prototype;f.toString=function(){return this.oa};f.equiv=function(a){return this.m(null,a)};f.m=function(a,b){return b instanceof Zb?this.oa===b.oa:!1};
f.call=function(){function a(a,b,c){return $b?$b(b,this,c):ac.call(null,b,this,c)}function b(a,b){return bc?bc(b,this):ac.call(null,b,this)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.g=a;return c}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return bc?bc(a,this):ac.call(null,a,this)};
f.a=function(a,b){return $b?$b(a,this,b):ac.call(null,a,this,b)};f.I=function(){return this.$};f.L=function(a,b){return new Zb(this.Y,this.name,this.oa,this.Pa,b)};f.F=function(){var a=this.Pa;return null!=a?a:this.Pa=a=Xb(Rb(this.name),Vb(this.Y))};f.D=function(a,b){return G(b,this.oa)};
function H(a){if(null==a)return null;if(null!=a&&(a.h&8388608||a.Lb))return a.P(null);if(Ba(a)||"string"===typeof a)return 0===a.length?null:new I(a,0);if(u(nb,a))return ob(a);throw Error([B(a),B(" is not ISeqable")].join(""));}function J(a){if(null==a)return null;if(null!=a&&(a.h&64||a.La))return a.W(null);a=H(a);return null==a?null:E(a)}function cc(a){return null!=a?null!=a&&(a.h&64||a.La)?a.ca(null):(a=H(a))?F(a):L:L}
function M(a){return null==a?null:null!=a&&(a.h&128||a.ab)?a.aa(null):H(cc(a))}var N=function N(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return N.b(arguments[0]);case 2:return N.a(arguments[0],arguments[1]);default:return N.s(arguments[0],arguments[1],new I(c.slice(2),0))}};N.b=function(){return!0};N.a=function(a,b){return null==a?null==b:a===b||lb(a,b)};
N.s=function(a,b,c){for(;;)if(N.a(a,b))if(M(c))a=b,b=J(c),c=M(c);else return N.a(b,J(c));else return!1};N.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return N.s(b,a,c)};N.G=2;function dc(a){this.w=a}dc.prototype.next=function(){if(null!=this.w){var a=J(this.w);this.w=M(this.w);return{value:a,done:!1}}return{value:null,done:!0}};function O(a){return new dc(H(a))}function ec(a,b){var c=Ob(a),c=Pb(0,c);return Qb(c,b)}
function fc(a){var b=0,c=1;for(a=H(a);;)if(null!=a)b+=1,c=Nb(31,c)+Wb(J(a))|0,a=M(a);else return ec(c,b)}var gc=ec(1,0);function hc(a){var b=0,c=0;for(a=H(a);;)if(null!=a)b+=1,c=c+Wb(J(a))|0,a=M(a);else return ec(c,b)}var ic=ec(0,0);Ma["null"]=!0;Na["null"]=function(){return 0};Date.prototype.m=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Date.prototype.Ua=!0;
Date.prototype.Qa=function(a,b){if(b instanceof Date)return ha(this.valueOf(),b.valueOf());throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};lb.number=function(a,b){return a===b};fb["function"]=!0;gb["function"]=function(){return null};mb._=function(a){return a[ca]||(a[ca]=++da)};function jc(a){return eb(a)}function kc(a,b){var c=Na(a);if(0===c)return b.B?b.B():b.call(null);for(var d=D.a(a,0),e=1;;)if(e<c)var g=D.a(a,e),d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}
function lc(a,b,c){var d=Na(a),e=c;for(c=0;;)if(c<d){var g=D.a(a,c),e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}function mc(a,b){var c=a.length;if(0===a.length)return b.B?b.B():b.call(null);for(var d=a[0],e=1;;)if(e<c)var g=a[e],d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}function nc(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c],e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}
function oc(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.a?b.a(c,g):b.call(null,c,g);d+=1}else return c}function pc(a){return null!=a?a.h&2||a.yb?!0:a.h?!1:u(Ma,a):u(Ma,a)}function rc(a){return null!=a?a.h&16||a.qb?!0:a.h?!1:u(Ra,a):u(Ra,a)}function sc(a,b){this.c=a;this.j=b}sc.prototype.ha=function(){return this.j<this.c.length};sc.prototype.next=function(){var a=this.c[this.j];this.j+=1;return a};function I(a,b){this.c=a;this.j=b;this.h=166199550;this.v=8192}f=I.prototype;f.toString=function(){return Mb(this)};
f.equiv=function(a){return this.m(null,a)};f.K=function(a,b){var c=b+this.j;return c<this.c.length?this.c[c]:null};f.ga=function(a,b,c){a=b+this.j;return a<this.c.length?this.c[a]:c};f.Ha=function(){return new sc(this.c,this.j)};f.aa=function(){return this.j+1<this.c.length?new I(this.c,this.j+1):null};f.X=function(){var a=this.c.length-this.j;return 0>a?0:a};f.bb=function(){var a=Na(this);return 0<a?new tc(this,a-1,null):null};f.F=function(){return fc(this)};
f.m=function(a,b){return uc.a?uc.a(this,b):uc.call(null,this,b)};f.R=function(){return L};f.U=function(a,b){return oc(this.c,b,this.c[this.j],this.j+1)};f.V=function(a,b,c){return oc(this.c,b,c,this.j)};f.W=function(){return this.c[this.j]};f.ca=function(){return this.j+1<this.c.length?new I(this.c,this.j+1):L};f.P=function(){return this.j<this.c.length?this:null};f.N=function(a,b){return P.a?P.a(b,this):P.call(null,b,this)};I.prototype[Ga]=function(){return O(this)};
function vc(a,b){return b<a.length?new I(a,b):null}function wc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return vc(arguments[0],0);case 2:return vc(arguments[0],arguments[1]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}function tc(a,b,c){this.Za=a;this.j=b;this.l=c;this.h=32374990;this.v=8192}f=tc.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};
f.aa=function(){return 0<this.j?new tc(this.Za,this.j-1,null):null};f.X=function(){return this.j+1};f.F=function(){return fc(this)};f.m=function(a,b){return uc.a?uc.a(this,b):uc.call(null,this,b)};f.R=function(){var a=this.l;return xc.a?xc.a(L,a):xc.call(null,L,a)};f.U=function(a,b){return yc?yc(b,this):zc.call(null,b,this)};f.V=function(a,b,c){return Ac?Ac(b,c,this):zc.call(null,b,c,this)};f.W=function(){return D.a(this.Za,this.j)};f.ca=function(){return 0<this.j?new tc(this.Za,this.j-1,null):L};
f.P=function(){return this};f.L=function(a,b){return new tc(this.Za,this.j,b)};f.N=function(a,b){return P.a?P.a(b,this):P.call(null,b,this)};tc.prototype[Ga]=function(){return O(this)};lb._=function(a,b){return a===b};var Q=function Q(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return Q.B();case 1:return Q.b(arguments[0]);case 2:return Q.a(arguments[0],arguments[1]);default:return Q.s(arguments[0],arguments[1],new I(c.slice(2),0))}};
Q.B=function(){return Bc};Q.b=function(a){return a};Q.a=function(a,b){return null!=a?Qa(a,b):Qa(L,b)};Q.s=function(a,b,c){for(;;)if(t(c))a=Q.a(a,b),b=J(c),c=M(c);else return Q.a(a,b)};Q.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return Q.s(b,a,c)};Q.G=2;
function S(a){if(null!=a)if(null!=a&&(a.h&2||a.yb))a=a.X(null);else if(Ba(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.h&8388608||a.Lb))a:{a=H(a);for(var b=0;;){if(pc(a)){a=b+Na(a);break a}a=M(a);b+=1}}else a=Na(a);else a=0;return a}function Cc(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return H(a)?J(a):c;if(rc(a))return D.g(a,b,c);if(H(a)){var d=M(a),e=b-1;a=d;b=e}else return c}}
function Dc(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.h&16||a.qb))return a.K(null,b);if(Ba(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.h&64||a.La)){var c;a:{c=a;for(var d=b;;){if(null==c)throw Error("Index out of bounds");if(0===d){if(H(c)){c=J(c);break a}throw Error("Index out of bounds");}if(rc(c)){c=D.a(c,d);break a}if(H(c))c=M(c),--d;else throw Error("Index out of bounds");
}}return c}if(u(Ra,a))return D.a(a,b);throw Error([B("nth not supported on this type "),B(Fa(Ea(a)))].join(""));}
function Ec(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return null;if(null!=a&&(a.h&16||a.qb))return a.ga(null,b,null);if(Ba(a))return b<a.length?a[b]:null;if("string"===typeof a)return b<a.length?a.charAt(b):null;if(null!=a&&(a.h&64||a.La))return Cc(a,b);if(u(Ra,a))return D.a(a,b);throw Error([B("nth not supported on this type "),B(Fa(Ea(a)))].join(""));}
function ac(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return bc(arguments[0],arguments[1]);case 3:return $b(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}function bc(a,b){return null==a?null:null!=a&&(a.h&256||a.Eb)?a.T(null,b):Ba(a)?b<a.length?a[b|0]:null:"string"===typeof a?b<a.length?a[b|0]:null:u(Va,a)?Wa.a(a,b):null}
function $b(a,b,c){return null!=a?null!=a&&(a.h&256||a.Eb)?a.H(null,b,c):Ba(a)?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:u(Va,a)?Wa.g(a,b,c):c:c}var Fc=function Fc(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 3:return Fc.g(arguments[0],arguments[1],arguments[2]);default:return Fc.s(arguments[0],arguments[1],arguments[2],new I(c.slice(3),0))}};
Fc.g=function(a,b,c){if(null!=a)a=Xa(a,b,c);else a:{a=[b];c=[c];b=a.length;var d=0,e;for(e=xb(Gc);;)if(d<b){var g=d+1;e=e.Wa(null,a[d],c[d]);d=g}else{a=zb(e);break a}}return a};Fc.s=function(a,b,c,d){for(;;)if(a=Fc.g(a,b,c),t(d))b=J(d),c=J(M(d)),d=M(M(d));else return a};Fc.C=function(a){var b=J(a),c=M(a);a=J(c);var d=M(c),c=J(d),d=M(d);return Fc.s(b,a,c,d)};Fc.G=3;function Hc(a,b){this.f=a;this.l=b;this.h=393217;this.v=0}f=Hc.prototype;f.I=function(){return this.l};
f.L=function(a,b){return new Hc(this.f,b)};
f.call=function(){function a(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K,R,ja){a=this;return Ic.$a?Ic.$a(a.f,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K,R,ja):Ic.call(null,a.f,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K,R,ja)}function b(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K,R){a=this;return a.f.Ba?a.f.Ba(b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K,R):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K,R)}function c(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K){a=this;return a.f.Aa?a.f.Aa(b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,
z,K):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z,K)}function d(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z){a=this;return a.f.za?a.f.za(b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C,z)}function e(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C){a=this;return a.f.ya?a.f.ya(b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A,C)}function g(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A){a=this;return a.f.xa?a.f.xa(b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A):a.f.call(null,
b,c,d,e,g,h,k,l,m,p,q,r,v,w,y,A)}function h(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y){a=this;return a.f.wa?a.f.wa(b,c,d,e,g,h,k,l,m,p,q,r,v,w,y):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v,w,y)}function k(a,b,c,d,e,g,h,k,l,m,p,q,r,v,w){a=this;return a.f.va?a.f.va(b,c,d,e,g,h,k,l,m,p,q,r,v,w):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v,w)}function l(a,b,c,d,e,g,h,k,l,m,p,q,r,v){a=this;return a.f.ua?a.f.ua(b,c,d,e,g,h,k,l,m,p,q,r,v):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r,v)}function p(a,b,c,d,e,g,h,k,l,m,p,q,r){a=this;
return a.f.ta?a.f.ta(b,c,d,e,g,h,k,l,m,p,q,r):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q,r)}function m(a,b,c,d,e,g,h,k,l,m,p,q){a=this;return a.f.sa?a.f.sa(b,c,d,e,g,h,k,l,m,p,q):a.f.call(null,b,c,d,e,g,h,k,l,m,p,q)}function q(a,b,c,d,e,g,h,k,l,m,p){a=this;return a.f.ra?a.f.ra(b,c,d,e,g,h,k,l,m,p):a.f.call(null,b,c,d,e,g,h,k,l,m,p)}function r(a,b,c,d,e,g,h,k,l,m){a=this;return a.f.Fa?a.f.Fa(b,c,d,e,g,h,k,l,m):a.f.call(null,b,c,d,e,g,h,k,l,m)}function v(a,b,c,d,e,g,h,k,l){a=this;return a.f.Ea?a.f.Ea(b,c,
d,e,g,h,k,l):a.f.call(null,b,c,d,e,g,h,k,l)}function w(a,b,c,d,e,g,h,k){a=this;return a.f.Da?a.f.Da(b,c,d,e,g,h,k):a.f.call(null,b,c,d,e,g,h,k)}function y(a,b,c,d,e,g,h){a=this;return a.f.Ca?a.f.Ca(b,c,d,e,g,h):a.f.call(null,b,c,d,e,g,h)}function A(a,b,c,d,e,g){a=this;return a.f.ba?a.f.ba(b,c,d,e,g):a.f.call(null,b,c,d,e,g)}function C(a,b,c,d,e){a=this;return a.f.S?a.f.S(b,c,d,e):a.f.call(null,b,c,d,e)}function K(a,b,c,d){a=this;return a.f.g?a.f.g(b,c,d):a.f.call(null,b,c,d)}function R(a,b,c){a=this;
return a.f.a?a.f.a(b,c):a.f.call(null,b,c)}function ja(a,b){a=this;return a.f.b?a.f.b(b):a.f.call(null,b)}function ub(a){a=this;return a.f.B?a.f.B():a.f.call(null)}var z=null,z=function(z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb,Ub,qc,Wc,xd,Fe,If){switch(arguments.length){case 1:return ub.call(this,z);case 2:return ja.call(this,z,X);case 3:return R.call(this,z,X,Y);case 4:return K.call(this,z,X,Y,Z);case 5:return C.call(this,z,X,Y,Z,ia);case 6:return A.call(this,z,X,Y,Z,ia,na);case 7:return y.call(this,
z,X,Y,Z,ia,na,qa);case 8:return w.call(this,z,X,Y,Z,ia,na,qa,sa);case 9:return v.call(this,z,X,Y,Z,ia,na,qa,sa,xa);case 10:return r.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da);case 11:return q.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja);case 12:return m.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa);case 13:return p.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za);case 14:return l.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb);case 15:return k.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb);case 16:return h.call(this,
z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb);case 17:return g.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb,Ub);case 18:return e.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb,Ub,qc);case 19:return d.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb,Ub,qc,Wc);case 20:return c.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb,Ub,qc,Wc,xd);case 21:return b.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,Ja,Sa,Za,hb,tb,Jb,Ub,qc,Wc,xd,Fe);case 22:return a.call(this,z,X,Y,Z,ia,na,qa,sa,xa,Da,
Ja,Sa,Za,hb,tb,Jb,Ub,qc,Wc,xd,Fe,If)}throw Error("Invalid arity: "+arguments.length);};z.b=ub;z.a=ja;z.g=R;z.S=K;z.ba=C;z.Ca=A;z.Da=y;z.Ea=w;z.Fa=v;z.ra=r;z.sa=q;z.ta=m;z.ua=p;z.va=l;z.wa=k;z.xa=h;z.ya=g;z.za=e;z.Aa=d;z.Ba=c;z.Db=b;z.$a=a;return z}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.B=function(){return this.f.B?this.f.B():this.f.call(null)};f.b=function(a){return this.f.b?this.f.b(a):this.f.call(null,a)};
f.a=function(a,b){return this.f.a?this.f.a(a,b):this.f.call(null,a,b)};f.g=function(a,b,c){return this.f.g?this.f.g(a,b,c):this.f.call(null,a,b,c)};f.S=function(a,b,c,d){return this.f.S?this.f.S(a,b,c,d):this.f.call(null,a,b,c,d)};f.ba=function(a,b,c,d,e){return this.f.ba?this.f.ba(a,b,c,d,e):this.f.call(null,a,b,c,d,e)};f.Ca=function(a,b,c,d,e,g){return this.f.Ca?this.f.Ca(a,b,c,d,e,g):this.f.call(null,a,b,c,d,e,g)};
f.Da=function(a,b,c,d,e,g,h){return this.f.Da?this.f.Da(a,b,c,d,e,g,h):this.f.call(null,a,b,c,d,e,g,h)};f.Ea=function(a,b,c,d,e,g,h,k){return this.f.Ea?this.f.Ea(a,b,c,d,e,g,h,k):this.f.call(null,a,b,c,d,e,g,h,k)};f.Fa=function(a,b,c,d,e,g,h,k,l){return this.f.Fa?this.f.Fa(a,b,c,d,e,g,h,k,l):this.f.call(null,a,b,c,d,e,g,h,k,l)};f.ra=function(a,b,c,d,e,g,h,k,l,p){return this.f.ra?this.f.ra(a,b,c,d,e,g,h,k,l,p):this.f.call(null,a,b,c,d,e,g,h,k,l,p)};
f.sa=function(a,b,c,d,e,g,h,k,l,p,m){return this.f.sa?this.f.sa(a,b,c,d,e,g,h,k,l,p,m):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m)};f.ta=function(a,b,c,d,e,g,h,k,l,p,m,q){return this.f.ta?this.f.ta(a,b,c,d,e,g,h,k,l,p,m,q):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q)};f.ua=function(a,b,c,d,e,g,h,k,l,p,m,q,r){return this.f.ua?this.f.ua(a,b,c,d,e,g,h,k,l,p,m,q,r):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r)};
f.va=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v){return this.f.va?this.f.va(a,b,c,d,e,g,h,k,l,p,m,q,r,v):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v)};f.wa=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w){return this.f.wa?this.f.wa(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w)};f.xa=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y){return this.f.xa?this.f.xa(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y)};
f.ya=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A){return this.f.ya?this.f.ya(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A)};f.za=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C){return this.f.za?this.f.za(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C)};
f.Aa=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K){return this.f.Aa?this.f.Aa(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K)};f.Ba=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R){return this.f.Ba?this.f.Ba(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R):this.f.call(null,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R)};
f.Db=function(a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja){return Ic.$a?Ic.$a(this.f,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja):Ic.call(null,this.f,a,b,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja)};function xc(a,b){return"function"==n(a)?new Hc(a,b):null==a?null:ib(a,b)}function Jc(a){var b=null!=a;return(b?null!=a?a.h&131072||a.Hb||(a.h?0:u(fb,a)):u(fb,a):b)?gb(a):null}function Kc(a){return null==a?!1:null!=a?a.h&8||a.Sb?!0:a.h?!1:u(Pa,a):u(Pa,a)}
function Lc(a){return null!=a?a.h&16777216||a.Yb?!0:a.h?!1:u(pb,a):u(pb,a)}function Mc(a){return null==a?!1:null!=a?a.h&1024||a.Fb?!0:a.h?!1:u(Ya,a):u(Ya,a)}function Nc(a){return null!=a?a.h&16384||a.Zb?!0:a.h?!1:u(cb,a):u(cb,a)}function Oc(a){return null!=a?a.v&512||a.Rb?!0:!1:!1}function Pc(a){var b=[];ea(a,function(a,b){return function(a,c){return b.push(c)}}(a,b));return b}function Qc(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var Rc={};
function Sc(a){return null==a?!1:null!=a?a.h&64||a.La?!0:a.h?!1:u(Ta,a):u(Ta,a)}function Tc(a){return null==a?!1:!1===a?!1:!0}
function Uc(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if("number"===typeof a){if("number"===typeof b)return ha(a,b);throw Error([B("Cannot compare "),B(a),B(" to "),B(b)].join(""));}if(null!=a?a.v&2048||a.Ua||(a.v?0:u(Cb,a)):u(Cb,a))return Db(a,b);if("string"!==typeof a&&!Ba(a)&&!0!==a&&!1!==a||Ea(a)!==Ea(b))throw Error([B("Cannot compare "),B(a),B(" to "),B(b)].join(""));return ha(a,b)}
function Vc(a,b){var c=S(a),d=S(b);if(c<d)c=-1;else if(c>d)c=1;else if(0===c)c=0;else a:for(d=0;;){var e=Uc(Dc(a,d),Dc(b,d));if(0===e&&d+1<c)d+=1;else{c=e;break a}}return c}function Xc(){return N.a(Uc,Uc)?Uc:function(a,b){var c=Uc.a?Uc.a(a,b):Uc.call(null,a,b);return"number"===typeof c?c:t(c)?-1:t(Uc.a?Uc.a(b,a):Uc.call(null,b,a))?1:0}}function Yc(a){if(H(a)){a=Zc.b?Zc.b(a):Zc.call(null,a);var b=Xc();ka(a,b);return H(a)}return L}
function zc(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return yc(arguments[0],arguments[1]);case 3:return Ac(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}function yc(a,b){var c=H(b);if(c){var d=J(c),c=M(c);return Ka?Ka(a,d,c):La.call(null,a,d,c)}return a.B?a.B():a.call(null)}
function Ac(a,b,c){for(c=H(c);;)if(c){var d=J(c);b=a.a?a.a(b,d):a.call(null,b,d);c=M(c)}else return b}function La(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return $c(arguments[0],arguments[1]);case 3:return Ka(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}
function $c(a,b){return null!=b&&(b.h&524288||b.Jb)?b.U(null,a):Ba(b)?mc(b,a):"string"===typeof b?mc(b,a):u(jb,b)?kb.a(b,a):yc(a,b)}function Ka(a,b,c){return null!=c&&(c.h&524288||c.Jb)?c.V(null,a,b):Ba(c)?nc(c,a,b):"string"===typeof c?nc(c,a,b):u(jb,c)?kb.g(c,a,b):Ac(a,b,c)}function ad(a){return a}
var bd=function bd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return bd.B();case 1:return bd.b(arguments[0]);case 2:return bd.a(arguments[0],arguments[1]);default:return bd.s(arguments[0],arguments[1],new I(c.slice(2),0))}};bd.B=function(){return 0};bd.b=function(a){return a};bd.a=function(a,b){return a+b};bd.s=function(a,b,c){return Ka(bd,a+b,c)};bd.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return bd.s(b,a,c)};bd.G=2;
var cd=function cd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return cd.b(arguments[0]);case 2:return cd.a(arguments[0],arguments[1]);default:return cd.s(arguments[0],arguments[1],new I(c.slice(2),0))}};cd.b=function(){return!0};cd.a=function(a,b){return a<b};cd.s=function(a,b,c){for(;;)if(a<b)if(M(c))a=b,b=J(c),c=M(c);else return b<J(c);else return!1};cd.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return cd.s(b,a,c)};cd.G=2;
var dd=function dd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return dd.b(arguments[0]);case 2:return dd.a(arguments[0],arguments[1]);default:return dd.s(arguments[0],arguments[1],new I(c.slice(2),0))}};dd.b=function(){return!0};dd.a=function(a,b){return a>=b};dd.s=function(a,b,c){for(;;)if(a>=b)if(M(c))a=b,b=J(c),c=M(c);else return b>=J(c);else return!1};dd.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return dd.s(b,a,c)};dd.G=2;
var ed=function ed(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return ed.b(arguments[0]);case 2:return ed.a(arguments[0],arguments[1]);default:return ed.s(arguments[0],arguments[1],new I(c.slice(2),0))}};ed.b=function(a){return a};ed.a=function(a,b){return a>b?a:b};ed.s=function(a,b,c){return Ka(ed,a>b?a:b,c)};ed.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return ed.s(b,a,c)};ed.G=2;
function fd(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function gd(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}var B=function B(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return B.B();case 1:return B.b(arguments[0]);default:return B.s(arguments[0],new I(c.slice(1),0))}};B.B=function(){return""};B.b=function(a){return null==a?"":""+a};
B.s=function(a,b){for(var c=new fa(""+B(a)),d=b;;)if(t(d))c=c.append(""+B(J(d))),d=M(d);else return c.toString()};B.C=function(a){var b=J(a);a=M(a);return B.s(b,a)};B.G=1;function uc(a,b){var c;if(Lc(b))if(pc(a)&&pc(b)&&S(a)!==S(b))c=!1;else a:{c=H(a);for(var d=H(b);;){if(null==c){c=null==d;break a}if(null!=d&&N.a(J(c),J(d)))c=M(c),d=M(d);else{c=!1;break a}}}else c=null;return Tc(c)}function hd(a,b,c,d,e){this.l=a;this.first=b;this.Ga=c;this.count=d;this.o=e;this.h=65937646;this.v=8192}f=hd.prototype;
f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};f.aa=function(){return 1===this.count?null:this.Ga};f.X=function(){return this.count};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return ib(L,this.l)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return this.first};f.ca=function(){return 1===this.count?L:this.Ga};f.P=function(){return this};
f.L=function(a,b){return new hd(b,this.first,this.Ga,this.count,this.o)};f.N=function(a,b){return new hd(this.l,b,this,this.count+1,null)};hd.prototype[Ga]=function(){return O(this)};function id(a){this.l=a;this.h=65937614;this.v=8192}f=id.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};f.aa=function(){return null};f.X=function(){return 0};f.F=function(){return gc};
f.m=function(a,b){return(null!=b?b.h&33554432||b.Wb||(b.h?0:u(qb,b)):u(qb,b))||Lc(b)?null==H(b):!1};f.R=function(){return this};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return null};f.ca=function(){return L};f.P=function(){return null};f.L=function(a,b){return new id(b)};f.N=function(a,b){return new hd(this.l,b,null,1,null)};var L=new id(null);id.prototype[Ga]=function(){return O(this)};
function jd(a){return(null!=a?a.h&134217728||a.Xb||(a.h?0:u(rb,a)):u(rb,a))?sb(a):Ka(Q,L,a)}function kd(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;a:{c=0<b.length?new I(b.slice(0),0):null;if(c instanceof I&&0===c.j)b=c.c;else b:for(b=[];;)if(null!=c)b.push(c.W(null)),c=c.aa(null);else break b;for(var c=b.length,e=L;;)if(0<c)d=c-1,e=e.N(null,b[c-1]),c=d;else break a}return e}
function ld(a,b,c,d){this.l=a;this.first=b;this.Ga=c;this.o=d;this.h=65929452;this.v=8192}f=ld.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};f.aa=function(){return null==this.Ga?null:H(this.Ga)};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.l)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return this.first};
f.ca=function(){return null==this.Ga?L:this.Ga};f.P=function(){return this};f.L=function(a,b){return new ld(b,this.first,this.Ga,this.o)};f.N=function(a,b){return new ld(null,b,this,null)};ld.prototype[Ga]=function(){return O(this)};function P(a,b){var c=null==b;return(c?c:null!=b&&(b.h&64||b.La))?new ld(null,a,b,null):new ld(null,a,H(b),null)}
function md(a,b){if(a.ma===b.ma)return 0;var c=Ca(a.Y);if(t(c?b.Y:c))return-1;if(t(a.Y)){if(Ca(b.Y))return 1;c=ha(a.Y,b.Y);return 0===c?ha(a.name,b.name):c}return ha(a.name,b.name)}function T(a,b,c,d){this.Y=a;this.name=b;this.ma=c;this.Pa=d;this.h=2153775105;this.v=4096}f=T.prototype;f.toString=function(){return[B(":"),B(this.ma)].join("")};f.equiv=function(a){return this.m(null,a)};f.m=function(a,b){return b instanceof T?this.ma===b.ma:!1};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return bc(c,this);case 3:return $b(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return bc(c,this)};a.g=function(a,c,d){return $b(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return bc(a,this)};f.a=function(a,b){return $b(a,this,b)};
f.F=function(){var a=this.Pa;return null!=a?a:this.Pa=a=Xb(Rb(this.name),Vb(this.Y))+2654435769|0};f.D=function(a,b){return G(b,[B(":"),B(this.ma)].join(""))};var nd=function nd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return nd.b(arguments[0]);case 2:return nd.a(arguments[0],arguments[1]);default:throw Error([B("Invalid arity: "),B(c.length)].join(""));}};
nd.b=function(a){if(a instanceof T)return a;if(a instanceof Zb){var b;if(null!=a&&(a.v&4096||a.Ib))b=a.Y;else throw Error([B("Doesn't support namespace: "),B(a)].join(""));return new T(b,od.b?od.b(a):od.call(null,a),a.oa,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new T(b[0],b[1],a,null):new T(null,b[0],a,null)):null};nd.a=function(a,b){return new T(a,b,[B(t(a)?[B(a),B("/")].join(""):null),B(b)].join(""),null)};nd.G=2;
function pd(a,b,c,d){this.l=a;this.Sa=b;this.w=c;this.o=d;this.h=32374988;this.v=1}f=pd.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};function qd(a){null!=a.Sa&&(a.w=a.Sa.B?a.Sa.B():a.Sa.call(null),a.Sa=null);return a.w}f.I=function(){return this.l};f.aa=function(){ob(this);return null==this.w?null:M(this.w)};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.l)};
f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){ob(this);return null==this.w?null:J(this.w)};f.ca=function(){ob(this);return null!=this.w?cc(this.w):L};f.P=function(){qd(this);if(null==this.w)return null;for(var a=this.w;;)if(a instanceof pd)a=qd(a);else return this.w=a,H(this.w)};f.L=function(a,b){return new pd(b,this.Sa,this.w,this.o)};f.N=function(a,b){return P(b,this)};pd.prototype[Ga]=function(){return O(this)};
function rd(a,b){this.hb=a;this.end=b;this.h=2;this.v=0}rd.prototype.add=function(a){this.hb[this.end]=a;return this.end+=1};rd.prototype.ia=function(){var a=new sd(this.hb,0,this.end);this.hb=null;return a};rd.prototype.X=function(){return this.end};function sd(a,b,c){this.c=a;this.M=b;this.end=c;this.h=524306;this.v=0}f=sd.prototype;f.X=function(){return this.end-this.M};f.K=function(a,b){return this.c[this.M+b]};f.ga=function(a,b,c){return 0<=b&&b<this.end-this.M?this.c[this.M+b]:c};
f.pb=function(){if(this.M===this.end)throw Error("-drop-first of empty chunk");return new sd(this.c,this.M+1,this.end)};f.U=function(a,b){return oc(this.c,b,this.c[this.M],this.M+1)};f.V=function(a,b,c){return oc(this.c,b,c,this.M)};function td(a,b,c,d){this.ia=a;this.na=b;this.l=c;this.o=d;this.h=31850732;this.v=1536}f=td.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};
f.aa=function(){if(1<Na(this.ia))return new td(Eb(this.ia),this.na,this.l,null);var a=ob(this.na);return null==a?null:a};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.l)};f.W=function(){return D.a(this.ia,0)};f.ca=function(){return 1<Na(this.ia)?new td(Eb(this.ia),this.na,this.l,null):null==this.na?L:this.na};f.P=function(){return this};f.jb=function(){return this.ia};f.kb=function(){return null==this.na?L:this.na};
f.L=function(a,b){return new td(this.ia,this.na,b,this.o)};f.N=function(a,b){return P(b,this)};f.ib=function(){return null==this.na?null:this.na};td.prototype[Ga]=function(){return O(this)};function ud(a,b){return 0===Na(a)?b:new td(a,b,null,null)}function vd(a,b){a.add(b)}function Zc(a){for(var b=[];;)if(H(a))b.push(J(a)),a=M(a);else return b}function wd(a,b){if(pc(a))return S(a);for(var c=a,d=b,e=0;;)if(0<d&&H(c))c=M(c),--d,e+=1;else return e}
var yd=function yd(b){return null==b?null:null==M(b)?H(J(b)):P(J(b),yd(M(b)))};function zd(a){return zb(a)}var Ad=function Ad(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 0:return Ad.B();case 1:return Ad.b(arguments[0]);case 2:return Ad.a(arguments[0],arguments[1]);default:return Ad.s(arguments[0],arguments[1],new I(c.slice(2),0))}};Ad.B=function(){return xb(Bc)};Ad.b=function(a){return a};Ad.a=function(a,b){return yb(a,b)};
Ad.s=function(a,b,c){for(;;)if(a=yb(a,b),t(c))b=J(c),c=M(c);else return a};Ad.C=function(a){var b=J(a),c=M(a);a=J(c);c=M(c);return Ad.s(b,a,c)};Ad.G=2;
function Bd(a,b,c){var d=H(c);if(0===b)return a.B?a.B():a.call(null);c=E(d);var e=F(d);if(1===b)return a.b?a.b(c):a.b?a.b(c):a.call(null,c);var d=E(e),g=F(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=E(g),h=F(g);if(3===b)return a.g?a.g(c,d,e):a.g?a.g(c,d,e):a.call(null,c,d,e);var g=E(h),k=F(h);if(4===b)return a.S?a.S(c,d,e,g):a.S?a.S(c,d,e,g):a.call(null,c,d,e,g);var h=E(k),l=F(k);if(5===b)return a.ba?a.ba(c,d,e,g,h):a.ba?a.ba(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=E(l),p=
F(l);if(6===b)return a.Ca?a.Ca(c,d,e,g,h,k):a.Ca?a.Ca(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=E(p),m=F(p);if(7===b)return a.Da?a.Da(c,d,e,g,h,k,l):a.Da?a.Da(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var p=E(m),q=F(m);if(8===b)return a.Ea?a.Ea(c,d,e,g,h,k,l,p):a.Ea?a.Ea(c,d,e,g,h,k,l,p):a.call(null,c,d,e,g,h,k,l,p);var m=E(q),r=F(q);if(9===b)return a.Fa?a.Fa(c,d,e,g,h,k,l,p,m):a.Fa?a.Fa(c,d,e,g,h,k,l,p,m):a.call(null,c,d,e,g,h,k,l,p,m);var q=E(r),v=F(r);if(10===b)return a.ra?a.ra(c,d,e,g,h,k,l,
p,m,q):a.ra?a.ra(c,d,e,g,h,k,l,p,m,q):a.call(null,c,d,e,g,h,k,l,p,m,q);var r=E(v),w=F(v);if(11===b)return a.sa?a.sa(c,d,e,g,h,k,l,p,m,q,r):a.sa?a.sa(c,d,e,g,h,k,l,p,m,q,r):a.call(null,c,d,e,g,h,k,l,p,m,q,r);var v=E(w),y=F(w);if(12===b)return a.ta?a.ta(c,d,e,g,h,k,l,p,m,q,r,v):a.ta?a.ta(c,d,e,g,h,k,l,p,m,q,r,v):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v);var w=E(y),A=F(y);if(13===b)return a.ua?a.ua(c,d,e,g,h,k,l,p,m,q,r,v,w):a.ua?a.ua(c,d,e,g,h,k,l,p,m,q,r,v,w):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w);var y=
E(A),C=F(A);if(14===b)return a.va?a.va(c,d,e,g,h,k,l,p,m,q,r,v,w,y):a.va?a.va(c,d,e,g,h,k,l,p,m,q,r,v,w,y):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y);var A=E(C),K=F(C);if(15===b)return a.wa?a.wa(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A):a.wa?a.wa(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A);var C=E(K),R=F(K);if(16===b)return a.xa?a.xa(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C):a.xa?a.xa(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C);var K=E(R),ja=F(R);if(17===
b)return a.ya?a.ya(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K):a.ya?a.ya(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K);var R=E(ja),ub=F(ja);if(18===b)return a.za?a.za(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R):a.za?a.za(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R);ja=E(ub);ub=F(ub);if(19===b)return a.Aa?a.Aa(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja):a.Aa?a.Aa(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y,
A,C,K,R,ja);var z=E(ub);F(ub);if(20===b)return a.Ba?a.Ba(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja,z):a.Ba?a.Ba(c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja,z):a.call(null,c,d,e,g,h,k,l,p,m,q,r,v,w,y,A,C,K,R,ja,z);throw Error("Only up to 20 arguments supported on functions");}
function Ic(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return Cd(arguments[0],arguments[1]);case 3:return Dd(arguments[0],arguments[1],arguments[2]);case 4:c=arguments[0];b=P(arguments[1],P(arguments[2],arguments[3]));d=c.G;if(c.C)var e=wd(b,d+1),c=e<=d?Bd(c,e,b):c.C(b);else c=c.apply(c,Zc(b));return c;case 5:return c=arguments[0],b=P(arguments[1],P(arguments[2],P(arguments[3],arguments[4]))),d=c.G,c.C?(e=wd(b,d+1),c=e<=d?Bd(c,e,b):
c.C(b)):c=c.apply(c,Zc(b)),c;default:return c=arguments[0],b=P(arguments[1],P(arguments[2],P(arguments[3],P(arguments[4],yd(new I(b.slice(5),0)))))),d=c.G,c.C?(e=wd(b,d+1),c=e<=d?Bd(c,e,b):c.C(b)):c=c.apply(c,Zc(b)),c}}function Cd(a,b){var c=a.G;if(a.C){var d=wd(b,c+1);return d<=c?Bd(a,d,b):a.C(b)}return a.apply(a,Zc(b))}function Dd(a,b,c){b=P(b,c);c=a.G;if(a.C){var d=wd(b,c+1);return d<=c?Bd(a,d,b):a.C(b)}return a.apply(a,Zc(b))}
var Ed=function Ed(){"undefined"===typeof la&&(la=function(b,c){this.Ob=b;this.Nb=c;this.h=393216;this.v=0},la.prototype.L=function(b,c){return new la(this.Ob,c)},la.prototype.I=function(){return this.Nb},la.prototype.ha=function(){return!1},la.prototype.next=function(){return Error("No such element")},la.prototype.remove=function(){return Error("Unsupported operation")},la.$b=function(){return new U(null,2,5,Fd,[xc(Gd,new ua(null,1,[Hd,kd(Id,kd(Bc))],null)),Jd],null)},la.vb=!0,la.fb="cljs.core/t_cljs$core9966",
la.Mb=function(b){return G(b,"cljs.core/t_cljs$core9966")});return new la(Ed,Kd)};function Ld(a,b){for(;;){if(null==H(b))return!0;var c;c=J(b);c=a.b?a.b(c):a.call(null,c);if(t(c)){c=a;var d=M(b);a=c;b=d}else return!1}}function Md(a,b){for(;;)if(H(b)){var c;c=J(b);c=a.b?a.b(c):a.call(null,c);if(t(c))return c;c=a;var d=M(b);a=c;b=d}else return null}function Nd(a,b,c,d){this.state=a;this.l=b;this.Qb=c;this.xb=d;this.v=16386;this.h=6455296}f=Nd.prototype;f.equiv=function(a){return this.m(null,a)};
f.m=function(a,b){return this===b};f.zb=function(){return this.state};f.I=function(){return this.l};f.sb=function(a,b,c){a=H(this.xb);for(var d=null,e=0,g=0;;)if(g<e){var h=d.K(null,g),k=Ec(h,0),h=Ec(h,1);h.S?h.S(k,this,b,c):h.call(null,k,this,b,c);g+=1}else if(a=H(a))Oc(a)?(d=Fb(a),a=Gb(a),k=d,e=S(d),d=k):(d=J(a),k=Ec(d,0),h=Ec(d,1),h.S?h.S(k,this,b,c):h.call(null,k,this,b,c),a=M(a),d=null,e=0),g=0;else return null};f.F=function(){return this[ca]||(this[ca]=++da)};
function Od(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Pd(arguments[0]);default:return c=arguments[0],b=new I(b.slice(1),0),d=null!=b&&(b.h&64||b.La)?Cd(Qd,b):b,b=bc(d,ya),d=bc(d,Rd),new Nd(c,b,d,null)}}function Pd(a){return new Nd(a,null,null,null)}
function Sd(a,b){if(a instanceof Nd){var c=a.Qb;if(null!=c&&!t(c.b?c.b(b):c.call(null,b)))throw Error([B("Assert failed: "),B("Validator rejected reference state"),B("\n"),B(function(){var a=kd(Td,Ud);return Vd.b?Vd.b(a):Vd.call(null,a)}())].join(""));c=a.state;a.state=b;null!=a.xb&&wb(a,c,b);return b}return Ib(a,b)}
var V=function V(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;switch(c.length){case 1:return V.b(arguments[0]);case 2:return V.a(arguments[0],arguments[1]);case 3:return V.g(arguments[0],arguments[1],arguments[2]);case 4:return V.S(arguments[0],arguments[1],arguments[2],arguments[3]);default:return V.s(arguments[0],arguments[1],arguments[2],arguments[3],new I(c.slice(4),0))}};
V.b=function(a){return function(b){return function(){function c(c,d){var e=a.b?a.b(d):a.call(null,d);return b.a?b.a(c,e):b.call(null,c,e)}function d(a){return b.b?b.b(a):b.call(null,a)}function e(){return b.B?b.B():b.call(null)}var g=null,h=function(){function c(a,b,e){var g=null;if(2<arguments.length){for(var g=0,h=Array(arguments.length-2);g<h.length;)h[g]=arguments[g+2],++g;g=new I(h,0)}return d.call(this,a,b,g)}function d(c,e,g){e=Dd(a,e,g);return b.a?b.a(c,e):b.call(null,c,e)}c.G=2;c.C=function(a){var b=
J(a);a=M(a);var c=J(a);a=cc(a);return d(b,c,a)};c.s=d;return c}(),g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var m=null;if(2<arguments.length){for(var m=0,q=Array(arguments.length-2);m<q.length;)q[m]=arguments[m+2],++m;m=new I(q,0)}return h.s(a,b,m)}throw Error("Invalid arity: "+arguments.length);};g.G=2;g.C=h.C;g.B=e;g.b=d;g.a=c;g.s=h.s;return g}()}};
V.a=function(a,b){return new pd(null,function(){var c=H(b);if(c){if(Oc(c)){for(var d=Fb(c),e=S(d),g=new rd(Array(e),0),h=0;;)if(h<e)vd(g,function(){var b=D.a(d,h);return a.b?a.b(b):a.call(null,b)}()),h+=1;else break;return ud(g.ia(),V.a(a,Gb(c)))}return P(function(){var b=J(c);return a.b?a.b(b):a.call(null,b)}(),V.a(a,cc(c)))}return null},null,null)};
V.g=function(a,b,c){return new pd(null,function(){var d=H(b),e=H(c);if(d&&e){var g=P,h;h=J(d);var k=J(e);h=a.a?a.a(h,k):a.call(null,h,k);d=g(h,V.g(a,cc(d),cc(e)))}else d=null;return d},null,null)};V.S=function(a,b,c,d){return new pd(null,function(){var e=H(b),g=H(c),h=H(d);if(e&&g&&h){var k=P,l;l=J(e);var p=J(g),m=J(h);l=a.g?a.g(l,p,m):a.call(null,l,p,m);e=k(l,V.S(a,cc(e),cc(g),cc(h)))}else e=null;return e},null,null)};
V.s=function(a,b,c,d,e){var g=function k(a){return new pd(null,function(){var b=V.a(H,a);return Ld(ad,b)?P(V.a(J,b),k(V.a(cc,b))):null},null,null)};return V.a(function(){return function(b){return Cd(a,b)}}(g),g(Q.s(e,d,wc([c,b],0))))};V.C=function(a){var b=J(a),c=M(a);a=J(c);var d=M(c),c=J(d),e=M(d),d=J(e),e=M(e);return V.s(b,a,c,d,e)};V.G=4;function Wd(a,b){return null!=a?null!=a&&(a.v&4||a.Tb)?xc(zd(Ka(yb,xb(a),b)),Jc(a)):Ka(Qa,a,b):Ka(Q,L,b)}function Xd(a,b){this.A=a;this.c=b}
function Yd(a){return new Xd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Zd(a){a=a.i;return 32>a?0:a-1>>>5<<5}function $d(a,b,c){for(;;){if(0===b)return c;var d=Yd(a);d.c[0]=c;c=d;b-=5}}var ae=function ae(b,c,d,e){var g=new Xd(d.A,Ha(d.c)),h=b.i-1>>>c&31;5===c?g.c[h]=e:(d=d.c[h],b=null!=d?ae(b,c-5,d,e):$d(null,c-5,e),g.c[h]=b);return g};
function be(a,b){throw Error([B("No item "),B(a),B(" in vector of length "),B(b)].join(""));}function ce(a,b){if(b>=Zd(a))return a.Z;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.c[b>>>d&31],d=e;else return c.c}function de(a,b){return 0<=b&&b<a.i?ce(a,b):be(b,a.i)}var ee=function ee(b,c,d,e,g){var h=new Xd(d.A,Ha(d.c));if(0===c)h.c[e&31]=g;else{var k=e>>>c&31;b=ee(b,c-5,d.c[k],e,g);h.c[k]=b}return h};function fe(a,b,c,d,e,g){this.j=a;this.gb=b;this.c=c;this.pa=d;this.start=e;this.end=g}
fe.prototype.ha=function(){return this.j<this.end};fe.prototype.next=function(){32===this.j-this.gb&&(this.c=ce(this.pa,this.j),this.gb+=32);var a=this.c[this.j&31];this.j+=1;return a};function U(a,b,c,d,e,g){this.l=a;this.i=b;this.shift=c;this.root=d;this.Z=e;this.o=g;this.h=167668511;this.v=8196}f=U.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.T=function(a,b){return Wa.g(this,b,null)};f.H=function(a,b,c){return"number"===typeof b?D.g(this,b,c):c};
f.K=function(a,b){return de(this,b)[b&31]};f.ga=function(a,b,c){return 0<=b&&b<this.i?ce(this,b)[b&31]:c};f.nb=function(a,b,c){if(0<=b&&b<this.i)return Zd(this)<=b?(a=Ha(this.Z),a[b&31]=c,new U(this.l,this.i,this.shift,this.root,a,null)):new U(this.l,this.i,this.shift,ee(this,this.shift,this.root,b,c),this.Z,null);if(b===this.i)return Qa(this,c);throw Error([B("Index "),B(b),B(" out of bounds  [0,"),B(this.i),B("]")].join(""));};
f.Ha=function(){var a=this.i;return new fe(0,0,0<S(this)?ce(this,0):null,this,0,a)};f.I=function(){return this.l};f.X=function(){return this.i};f.lb=function(){return D.a(this,0)};f.mb=function(){return D.a(this,1)};f.bb=function(){return 0<this.i?new tc(this,this.i-1,null):null};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};
f.m=function(a,b){if(b instanceof U)if(this.i===S(b))for(var c=Kb(this),d=Kb(b);;)if(t(c.ha())){var e=c.next(),g=d.next();if(!N.a(e,g))return!1}else return!0;else return!1;else return uc(this,b)};f.Va=function(){return new ge(this.i,this.shift,he.b?he.b(this.root):he.call(null,this.root),ie.b?ie.b(this.Z):ie.call(null,this.Z))};f.R=function(){return xc(Bc,this.l)};f.U=function(a,b){return kc(this,b)};
f.V=function(a,b,c){a=0;for(var d=c;;)if(a<this.i){var e=ce(this,a);c=e.length;a:for(var g=0;;)if(g<c)var h=e[g],d=b.a?b.a(d,h):b.call(null,d,h),g=g+1;else{e=d;break a}a+=c;d=e}else return d};f.Ta=function(a,b,c){if("number"===typeof b)return db(this,b,c);throw Error("Vector's key for assoc must be a number.");};
f.P=function(){if(0===this.i)return null;if(32>=this.i)return new I(this.Z,0);var a;a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.c[0];else{a=a.c;break a}}return je?je(this,a,0,0):ke.call(null,this,a,0,0)};f.L=function(a,b){return new U(b,this.i,this.shift,this.root,this.Z,this.o)};
f.N=function(a,b){if(32>this.i-Zd(this)){for(var c=this.Z.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.Z[e],e+=1;else break;d[c]=b;return new U(this.l,this.i+1,this.shift,this.root,d,null)}c=(d=this.i>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Yd(null),d.c[0]=this.root,e=$d(null,this.shift,new Xd(null,this.Z)),d.c[1]=e):d=ae(this,this.shift,this.root,new Xd(null,this.Z));return new U(this.l,this.i+1,c,d,[b],null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.ga(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.K(null,c)};a.g=function(a,c,d){return this.ga(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return this.K(null,a)};f.a=function(a,b){return this.ga(null,a,b)};
var Fd=new Xd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Bc=new U(null,0,5,Fd,[],gc);U.prototype[Ga]=function(){return O(this)};function le(a){if(Ba(a))a:{var b=a.length;if(32>b)a=new U(null,b,5,Fd,a,null);else for(var c=32,d=(new U(null,32,5,Fd,a.slice(0,32),null)).Va(null);;)if(c<b)var e=c+1,d=Ad.a(d,a[c]),c=e;else{a=zb(d);break a}}else a=zb(Ka(yb,xb(Bc),a));return a}
function me(a,b,c,d,e,g){this.fa=a;this.node=b;this.j=c;this.M=d;this.l=e;this.o=g;this.h=32375020;this.v=1536}f=me.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};f.aa=function(){if(this.M+1<this.node.length){var a;a=this.fa;var b=this.node,c=this.j,d=this.M+1;a=je?je(a,b,c,d):ke.call(null,a,b,c,d);return null==a?null:a}return Hb(this)};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};
f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(Bc,this.l)};f.U=function(a,b){var c;c=this.fa;var d=this.j+this.M,e=S(this.fa);c=ne?ne(c,d,e):oe.call(null,c,d,e);return kc(c,b)};f.V=function(a,b,c){a=this.fa;var d=this.j+this.M,e=S(this.fa);a=ne?ne(a,d,e):oe.call(null,a,d,e);return lc(a,b,c)};f.W=function(){return this.node[this.M]};
f.ca=function(){if(this.M+1<this.node.length){var a;a=this.fa;var b=this.node,c=this.j,d=this.M+1;a=je?je(a,b,c,d):ke.call(null,a,b,c,d);return null==a?L:a}return Gb(this)};f.P=function(){return this};f.jb=function(){var a=this.node;return new sd(a,this.M,a.length)};f.kb=function(){var a=this.j+this.node.length;if(a<Na(this.fa)){var b=this.fa,c=ce(this.fa,a);return je?je(b,c,a,0):ke.call(null,b,c,a,0)}return L};
f.L=function(a,b){return pe?pe(this.fa,this.node,this.j,this.M,b):ke.call(null,this.fa,this.node,this.j,this.M,b)};f.N=function(a,b){return P(b,this)};f.ib=function(){var a=this.j+this.node.length;if(a<Na(this.fa)){var b=this.fa,c=ce(this.fa,a);return je?je(b,c,a,0):ke.call(null,b,c,a,0)}return null};me.prototype[Ga]=function(){return O(this)};
function ke(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 3:return b=arguments[0],c=arguments[1],d=arguments[2],new me(b,de(b,c),c,d,null,null);case 4:return je(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return pe(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}function je(a,b,c,d){return new me(a,b,c,d,null,null)}
function pe(a,b,c,d,e){return new me(a,b,c,d,e,null)}function qe(a,b,c,d,e){this.l=a;this.pa=b;this.start=c;this.end=d;this.o=e;this.h=167666463;this.v=8192}f=qe.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.T=function(a,b){return Wa.g(this,b,null)};f.H=function(a,b,c){return"number"===typeof b?D.g(this,b,c):c};f.K=function(a,b){return 0>b||this.end<=this.start+b?be(b,this.end-this.start):D.a(this.pa,this.start+b)};
f.ga=function(a,b,c){return 0>b||this.end<=this.start+b?c:D.g(this.pa,this.start+b,c)};f.nb=function(a,b,c){var d=this.start+b;a=this.l;c=Fc.g(this.pa,d,c);b=this.start;var e=this.end,d=d+1,d=e>d?e:d;return re.ba?re.ba(a,c,b,d,null):re.call(null,a,c,b,d,null)};f.I=function(){return this.l};f.X=function(){return this.end-this.start};f.bb=function(){return this.start!==this.end?new tc(this,this.end-this.start-1,null):null};f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};
f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(Bc,this.l)};f.U=function(a,b){return kc(this,b)};f.V=function(a,b,c){return lc(this,b,c)};f.Ta=function(a,b,c){if("number"===typeof b)return db(this,b,c);throw Error("Subvec's key for assoc must be a number.");};f.P=function(){var a=this;return function(b){return function d(e){return e===a.end?null:P(D.a(a.pa,e),new pd(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};
f.L=function(a,b){return re.ba?re.ba(b,this.pa,this.start,this.end,this.o):re.call(null,b,this.pa,this.start,this.end,this.o)};f.N=function(a,b){var c=this.l,d=db(this.pa,this.end,b),e=this.start,g=this.end+1;return re.ba?re.ba(c,d,e,g,null):re.call(null,c,d,e,g,null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.ga(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.K(null,c)};a.g=function(a,c,d){return this.ga(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return this.K(null,a)};f.a=function(a,b){return this.ga(null,a,b)};qe.prototype[Ga]=function(){return O(this)};
function re(a,b,c,d,e){for(;;)if(b instanceof qe)c=b.start+c,d=b.start+d,b=b.pa;else{var g=S(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new qe(a,b,c,d,e)}}function oe(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 2:return b=arguments[0],ne(b,arguments[1],S(b));case 3:return ne(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}
function ne(a,b,c){return re(null,a,b,c,null)}function se(a,b){return a===b.A?b:new Xd(a,Ha(b.c))}function he(a){return new Xd({},Ha(a.c))}function ie(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Qc(a,0,b,0,a.length);return b}var te=function te(b,c,d,e){d=se(b.root.A,d);var g=b.i-1>>>c&31;if(5===c)b=e;else{var h=d.c[g];b=null!=h?te(b,c-5,h,e):$d(b.root.A,c-5,e)}d.c[g]=b;return d};
function ge(a,b,c,d){this.i=a;this.shift=b;this.root=c;this.Z=d;this.v=88;this.h=275}f=ge.prototype;
f.cb=function(a,b){if(this.root.A){if(32>this.i-Zd(this))this.Z[this.i&31]=b;else{var c=new Xd(this.root.A,this.Z),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.Z=d;if(this.i>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=$d(this.root.A,this.shift,c);this.root=new Xd(this.root.A,d);this.shift=e}else this.root=te(this,this.shift,this.root,c)}this.i+=1;return this}throw Error("conj! after persistent!");};f.eb=function(){if(this.root.A){this.root.A=null;var a=this.i-Zd(this),b=Array(a);Qc(this.Z,0,b,0,a);return new U(null,this.i,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Wa=function(a,b,c){if("number"===typeof b)return Bb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.rb=function(a,b,c){var d=this;if(d.root.A){if(0<=b&&b<d.i)return Zd(this)<=b?d.Z[b&31]=c:(a=function(){return function g(a,k){var l=se(d.root.A,k);if(0===a)l.c[b&31]=c;else{var p=b>>>a&31,m=g(a-5,l.c[p]);l.c[p]=m}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.i)return yb(this,c);throw Error([B("Index "),B(b),B(" out of bounds for TransientVector of length"),B(d.i)].join(""));}throw Error("assoc! after persistent!");};
f.X=function(){if(this.root.A)return this.i;throw Error("count after persistent!");};f.K=function(a,b){if(this.root.A)return de(this,b)[b&31];throw Error("nth after persistent!");};f.ga=function(a,b,c){return 0<=b&&b<this.i?D.a(this,b):c};f.T=function(a,b){return Wa.g(this,b,null)};f.H=function(a,b,c){return"number"===typeof b?D.g(this,b,c):c};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.T(null,c);case 3:return this.H(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.T(null,c)};a.g=function(a,c,d){return this.H(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return this.T(null,a)};f.a=function(a,b){return this.H(null,a,b)};function ue(){this.h=2097152;this.v=0}
ue.prototype.equiv=function(a){return this.m(null,a)};ue.prototype.m=function(){return!1};var ve=new ue;function we(a,b){return Tc(Mc(b)?S(a)===S(b)?Ld(ad,V.a(function(a){return N.a($b(b,J(a),ve),J(M(a)))},a)):null:null)}function xe(a){this.w=a}xe.prototype.next=function(){if(null!=this.w){var a=J(this.w),b=Ec(a,0),a=Ec(a,1);this.w=M(this.w);return{value:[b,a],done:!1}}return{value:null,done:!0}};function ye(a){return new xe(H(a))}
function ze(a,b){var c;if(b instanceof T)a:{c=a.length;for(var d=b.ma,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof T&&d===a[e].ma){c=e;break a}e+=2}}else if("string"==typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(b===a[d]){c=d;break a}d+=2}else if(b instanceof Zb)a:for(c=a.length,d=b.oa,e=0;;){if(c<=e){c=-1;break a}if(a[e]instanceof Zb&&d===a[e].oa){c=e;break a}e+=2}else if(null==b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(null==a[d]){c=d;break a}d+=2}else a:for(c=
a.length,d=0;;){if(c<=d){c=-1;break a}if(N.a(b,a[d])){c=d;break a}d+=2}return c}function Ae(a,b,c){this.c=a;this.j=b;this.$=c;this.h=32374990;this.v=0}f=Ae.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.$};f.aa=function(){return this.j<this.c.length-2?new Ae(this.c,this.j+2,this.$):null};f.X=function(){return(this.c.length-this.j)/2};f.F=function(){return fc(this)};f.m=function(a,b){return uc(this,b)};
f.R=function(){return xc(L,this.$)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return new U(null,2,5,Fd,[this.c[this.j],this.c[this.j+1]],null)};f.ca=function(){return this.j<this.c.length-2?new Ae(this.c,this.j+2,this.$):L};f.P=function(){return this};f.L=function(a,b){return new Ae(this.c,this.j,b)};f.N=function(a,b){return P(b,this)};Ae.prototype[Ga]=function(){return O(this)};function Be(a,b,c){this.c=a;this.j=b;this.i=c}
Be.prototype.ha=function(){return this.j<this.i};Be.prototype.next=function(){var a=new U(null,2,5,Fd,[this.c[this.j],this.c[this.j+1]],null);this.j+=2;return a};function ua(a,b,c,d){this.l=a;this.i=b;this.c=c;this.o=d;this.h=16647951;this.v=8196}f=ua.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.keys=function(){return O(Ce.b?Ce.b(this):Ce.call(null,this))};f.entries=function(){return ye(H(this))};
f.values=function(){return O(De.b?De.b(this):De.call(null,this))};f.has=function(a){return $b(this,a,Rc)===Rc?!1:!0};f.get=function(a,b){return this.H(null,a,b)};f.forEach=function(a){for(var b=H(this),c=null,d=0,e=0;;)if(e<d){var g=c.K(null,e),h=Ec(g,0),g=Ec(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=H(b))Oc(b)?(c=Fb(b),b=Gb(b),h=c,d=S(c),c=h):(c=J(b),h=Ec(c,0),g=Ec(c,1),a.a?a.a(g,h):a.call(null,g,h),b=M(b),c=null,d=0),e=0;else return null};f.T=function(a,b){return Wa.g(this,b,null)};
f.H=function(a,b,c){a=ze(this.c,b);return-1===a?c:this.c[a+1]};f.Ha=function(){return new Be(this.c,0,2*this.i)};f.I=function(){return this.l};f.X=function(){return this.i};f.F=function(){var a=this.o;return null!=a?a:this.o=a=hc(this)};f.m=function(a,b){if(null!=b&&(b.h&1024||b.Fb)){var c=this.c.length;if(this.i===b.X(null))for(var d=0;;)if(d<c){var e=b.H(null,this.c[d],Rc);if(e!==Rc)if(N.a(this.c[d+1],e))d+=2;else return!1;else return!1}else return!0;else return!1}else return we(this,b)};
f.Va=function(){return new Ee({},this.c.length,Ha(this.c))};f.R=function(){return ib(Kd,this.l)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.Ta=function(a,b,c){a=ze(this.c,b);if(-1===a){if(this.i<Ge){a=this.c;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new ua(this.l,this.i+1,e,null)}return ib(Xa(Wd(Gc,this),b,c),this.l)}if(c===this.c[a+1])return this;b=Ha(this.c);b[a+1]=c;return new ua(this.l,this.i,b,null)};
f.P=function(){var a=this.c;return 0<=a.length-2?new Ae(a,0,null):null};f.L=function(a,b){return new ua(b,this.i,this.c,this.o)};f.N=function(a,b){if(Nc(b))return Xa(this,D.a(b,0),D.a(b,1));for(var c=this,d=H(b);;){if(null==d)return c;var e=J(d);if(Nc(e))c=Xa(c,D.a(e,0),D.a(e,1)),d=M(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.T(null,c);case 3:return this.H(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.T(null,c)};a.g=function(a,c,d){return this.H(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return this.T(null,a)};f.a=function(a,b){return this.H(null,a,b)};var Kd=new ua(null,0,[],ic),Ge=8;ua.prototype[Ga]=function(){return O(this)};
function Ee(a,b,c){this.Ra=a;this.Oa=b;this.c=c;this.h=258;this.v=56}f=Ee.prototype;f.X=function(){if(t(this.Ra))return fd(this.Oa);throw Error("count after persistent!");};f.T=function(a,b){return Wa.g(this,b,null)};f.H=function(a,b,c){if(t(this.Ra))return a=ze(this.c,b),-1===a?c:this.c[a+1];throw Error("lookup after persistent!");};
f.cb=function(a,b){if(t(this.Ra)){if(null!=b?b.h&2048||b.Gb||(b.h?0:u($a,b)):u($a,b))return Ab(this,He.b?He.b(b):He.call(null,b),Ie.b?Ie.b(b):Ie.call(null,b));for(var c=H(b),d=this;;){var e=J(c);if(t(e))c=M(c),d=Ab(d,He.b?He.b(e):He.call(null,e),Ie.b?Ie.b(e):Ie.call(null,e));else return d}}else throw Error("conj! after persistent!");};f.eb=function(){if(t(this.Ra))return this.Ra=!1,new ua(null,fd(this.Oa),this.c,null);throw Error("persistent! called twice");};
f.Wa=function(a,b,c){if(t(this.Ra)){a=ze(this.c,b);if(-1===a){if(this.Oa+2<=2*Ge)return this.Oa+=2,this.c.push(b),this.c.push(c),this;a=Je.a?Je.a(this.Oa,this.c):Je.call(null,this.Oa,this.c);return Ab(a,b,c)}c!==this.c[a+1]&&(this.c[a+1]=c);return this}throw Error("assoc! after persistent!");};function Je(a,b){for(var c=xb(Gc),d=0;;)if(d<a)c=Ab(c,b[d],b[d+1]),d+=2;else return c}function Ke(){this.qa=!1}
function Le(a,b){return a===b?!0:a===b||a instanceof T&&b instanceof T&&a.ma===b.ma?!0:N.a(a,b)}function Me(a,b,c){a=Ha(a);a[b]=c;return a}function Ne(a,b,c,d){a=a.Ma(b);a.c[c]=d;return a}function Oe(a,b,c,d){this.c=a;this.j=b;this.Ya=c;this.la=d}Oe.prototype.advance=function(){for(var a=this.c.length;;)if(this.j<a){var b=this.c[this.j],c=this.c[this.j+1];null!=b?b=this.Ya=new U(null,2,5,Fd,[b,c],null):null!=c?(b=Kb(c),b=b.ha()?this.la=b:!1):b=!1;this.j+=2;if(b)return!0}else return!1};
Oe.prototype.ha=function(){var a=null!=this.Ya;return a?a:(a=null!=this.la)?a:this.advance()};Oe.prototype.next=function(){if(null!=this.Ya){var a=this.Ya;this.Ya=null;return a}if(null!=this.la)return a=this.la.next(),this.la.ha()||(this.la=null),a;if(this.advance())return this.next();throw Error("No such element");};Oe.prototype.remove=function(){return Error("Unsupported operation")};function Pe(a,b,c){this.A=a;this.J=b;this.c=c}f=Pe.prototype;
f.Ma=function(a){if(a===this.A)return this;var b=gd(this.J),c=Array(0>b?4:2*(b+1));Qc(this.c,0,c,0,2*b);return new Pe(a,this.J,c)};f.Xa=function(){return Qe?Qe(this.c):Re.call(null,this.c)};f.Na=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.J&e))return d;var g=gd(this.J&e-1),e=this.c[2*g],g=this.c[2*g+1];return null==e?g.Na(a+5,b,c,d):Le(c,e)?g:d};
f.ka=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=gd(this.J&h-1);if(0===(this.J&h)){var l=gd(this.J);if(2*l<this.c.length){a=this.Ma(a);b=a.c;g.qa=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.J|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Se.ka(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.J>>>d&1)&&(k[d]=null!=this.c[e]?Se.ka(a,b+5,Wb(this.c[e]),this.c[e],this.c[e+1],g):this.c[e+1],e+=2),d+=1;else break;return new Te(a,l+1,k)}b=Array(2*(l+4));Qc(this.c,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;Qc(this.c,2*k,b,2*(k+1),2*(l-k));g.qa=!0;a=this.Ma(a);a.c=b;a.J|=h;return a}l=this.c[2*k];h=this.c[2*k+1];if(null==l)return l=h.ka(a,b+5,c,d,e,g),l===h?this:Ne(this,a,2*k+1,l);if(Le(d,l))return e===h?this:Ne(this,a,2*k+1,e);g.qa=!0;g=b+5;d=Ue?Ue(a,g,l,h,c,d,e):Ve.call(null,a,g,l,h,c,d,e);e=2*k;k=
2*k+1;a=this.Ma(a);a.c[e]=null;a.c[k]=d;return a};
f.ja=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=gd(this.J&g-1);if(0===(this.J&g)){var k=gd(this.J);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Se.ja(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.J>>>c&1)&&(h[c]=null!=this.c[d]?Se.ja(a+5,Wb(this.c[d]),this.c[d],this.c[d+1],e):this.c[d+1],d+=2),c+=1;else break;return new Te(null,k+1,h)}a=Array(2*(k+1));Qc(this.c,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;Qc(this.c,2*h,a,2*(h+1),2*(k-h));e.qa=!0;return new Pe(null,this.J|g,a)}var l=this.c[2*h],g=this.c[2*h+1];if(null==l)return k=g.ja(a+5,b,c,d,e),k===g?this:new Pe(null,this.J,Me(this.c,2*h+1,k));if(Le(c,l))return d===g?this:new Pe(null,this.J,Me(this.c,2*h+1,d));e.qa=!0;e=this.J;k=this.c;a+=5;a=We?We(a,l,g,b,c,d):Ve.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=Ha(k);d[c]=null;d[h]=a;return new Pe(null,e,d)};f.Ha=function(){return new Oe(this.c,0,null,null)};
var Se=new Pe(null,0,[]);function Xe(a,b,c){this.c=a;this.j=b;this.la=c}Xe.prototype.ha=function(){for(var a=this.c.length;;){if(null!=this.la&&this.la.ha())return!0;if(this.j<a){var b=this.c[this.j];this.j+=1;null!=b&&(this.la=Kb(b))}else return!1}};Xe.prototype.next=function(){if(this.ha())return this.la.next();throw Error("No such element");};Xe.prototype.remove=function(){return Error("Unsupported operation")};function Te(a,b,c){this.A=a;this.i=b;this.c=c}f=Te.prototype;
f.Ma=function(a){return a===this.A?this:new Te(a,this.i,Ha(this.c))};f.Xa=function(){return Ye?Ye(this.c):Ze.call(null,this.c)};f.Na=function(a,b,c,d){var e=this.c[b>>>a&31];return null!=e?e.Na(a+5,b,c,d):d};f.ka=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.c[h];if(null==k)return a=Ne(this,a,h,Se.ka(a,b+5,c,d,e,g)),a.i+=1,a;b=k.ka(a,b+5,c,d,e,g);return b===k?this:Ne(this,a,h,b)};
f.ja=function(a,b,c,d,e){var g=b>>>a&31,h=this.c[g];if(null==h)return new Te(null,this.i+1,Me(this.c,g,Se.ja(a+5,b,c,d,e)));a=h.ja(a+5,b,c,d,e);return a===h?this:new Te(null,this.i,Me(this.c,g,a))};f.Ha=function(){return new Xe(this.c,0,null)};function $e(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Le(c,a[d]))return d;d+=2}else return-1}function af(a,b,c,d){this.A=a;this.Ia=b;this.i=c;this.c=d}f=af.prototype;
f.Ma=function(a){if(a===this.A)return this;var b=Array(2*(this.i+1));Qc(this.c,0,b,0,2*this.i);return new af(a,this.Ia,this.i,b)};f.Xa=function(){return Qe?Qe(this.c):Re.call(null,this.c)};f.Na=function(a,b,c,d){a=$e(this.c,this.i,c);return 0>a?d:Le(c,this.c[a])?this.c[a+1]:d};
f.ka=function(a,b,c,d,e,g){if(c===this.Ia){b=$e(this.c,this.i,d);if(-1===b){if(this.c.length>2*this.i)return b=2*this.i,c=2*this.i+1,a=this.Ma(a),a.c[b]=d,a.c[c]=e,g.qa=!0,a.i+=1,a;c=this.c.length;b=Array(c+2);Qc(this.c,0,b,0,c);b[c]=d;b[c+1]=e;g.qa=!0;d=this.i+1;a===this.A?(this.c=b,this.i=d,a=this):a=new af(this.A,this.Ia,d,b);return a}return this.c[b+1]===e?this:Ne(this,a,b+1,e)}return(new Pe(a,1<<(this.Ia>>>b&31),[null,this,null,null])).ka(a,b,c,d,e,g)};
f.ja=function(a,b,c,d,e){return b===this.Ia?(a=$e(this.c,this.i,c),-1===a?(a=2*this.i,b=Array(a+2),Qc(this.c,0,b,0,a),b[a]=c,b[a+1]=d,e.qa=!0,new af(null,this.Ia,this.i+1,b)):N.a(this.c[a],d)?this:new af(null,this.Ia,this.i,Me(this.c,a+1,d))):(new Pe(null,1<<(this.Ia>>>a&31),[null,this])).ja(a,b,c,d,e)};f.Ha=function(){return new Oe(this.c,0,null,null)};
function Ve(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 6:return We(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Ue(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}
function We(a,b,c,d,e,g){var h=Wb(b);if(h===d)return new af(null,h,2,[b,c,e,g]);var k=new Ke;return Se.ja(a,h,b,c,k).ja(a,d,e,g,k)}function Ue(a,b,c,d,e,g,h){var k=Wb(c);if(k===e)return new af(null,k,2,[c,d,g,h]);var l=new Ke;return Se.ka(a,b,k,c,d,l).ka(a,b,e,g,h,l)}function bf(a,b,c,d,e){this.l=a;this.Ja=b;this.j=c;this.w=d;this.o=e;this.h=32374860;this.v=0}f=bf.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};
f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.l)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return null==this.w?new U(null,2,5,Fd,[this.Ja[this.j],this.Ja[this.j+1]],null):J(this.w)};f.ca=function(){if(null==this.w){var a=this.Ja,b=this.j+2;return cf?cf(a,b,null):Re.call(null,a,b,null)}var a=this.Ja,b=this.j,c=M(this.w);return cf?cf(a,b,c):Re.call(null,a,b,c)};
f.P=function(){return this};f.L=function(a,b){return new bf(b,this.Ja,this.j,this.w,this.o)};f.N=function(a,b){return P(b,this)};bf.prototype[Ga]=function(){return O(this)};function Re(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Qe(arguments[0]);case 3:return cf(arguments[0],arguments[1],arguments[2]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}function Qe(a){return cf(a,0,null)}
function cf(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new bf(null,a,b,null,null);var d=a[b+1];if(t(d)&&(d=d.Xa(),t(d)))return new bf(null,a,b+2,d,null);b+=2}else return null;else return new bf(null,a,b,c,null)}function df(a,b,c,d,e){this.l=a;this.Ja=b;this.j=c;this.w=d;this.o=e;this.h=32374860;this.v=0}f=df.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.l};
f.F=function(){var a=this.o;return null!=a?a:this.o=a=fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.l)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return J(this.w)};f.ca=function(){var a=this.Ja,b=this.j,c=M(this.w);return ef?ef(null,a,b,c):Ze.call(null,null,a,b,c)};f.P=function(){return this};f.L=function(a,b){return new df(b,this.Ja,this.j,this.w,this.o)};f.N=function(a,b){return P(b,this)};df.prototype[Ga]=function(){return O(this)};
function Ze(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;switch(b.length){case 1:return Ye(arguments[0]);case 4:return ef(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error([B("Invalid arity: "),B(b.length)].join(""));}}function Ye(a){return ef(null,a,0,null)}function ef(a,b,c,d){if(null==d)for(d=b.length;;)if(c<d){var e=b[c];if(t(e)&&(e=e.Xa(),t(e)))return new df(a,b,c+1,e,null);c+=1}else return null;else return new df(a,b,c,d,null)}
function ff(a,b,c){this.da=a;this.wb=b;this.ob=c}ff.prototype.ha=function(){return this.ob&&this.wb.ha()};ff.prototype.next=function(){if(this.ob)return this.wb.next();this.ob=!0;return this.da};ff.prototype.remove=function(){return Error("Unsupported operation")};function gf(a,b,c,d,e,g){this.l=a;this.i=b;this.root=c;this.ea=d;this.da=e;this.o=g;this.h=16123663;this.v=8196}f=gf.prototype;f.toString=function(){return Mb(this)};f.equiv=function(a){return this.m(null,a)};
f.keys=function(){return O(Ce.b?Ce.b(this):Ce.call(null,this))};f.entries=function(){return ye(H(this))};f.values=function(){return O(De.b?De.b(this):De.call(null,this))};f.has=function(a){return $b(this,a,Rc)===Rc?!1:!0};f.get=function(a,b){return this.H(null,a,b)};
f.forEach=function(a){for(var b=H(this),c=null,d=0,e=0;;)if(e<d){var g=c.K(null,e),h=Ec(g,0),g=Ec(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=H(b))Oc(b)?(c=Fb(b),b=Gb(b),h=c,d=S(c),c=h):(c=J(b),h=Ec(c,0),g=Ec(c,1),a.a?a.a(g,h):a.call(null,g,h),b=M(b),c=null,d=0),e=0;else return null};f.T=function(a,b){return Wa.g(this,b,null)};f.H=function(a,b,c){return null==b?this.ea?this.da:c:null==this.root?c:this.root.Na(0,Wb(b),b,c)};
f.Ha=function(){var a=this.root?Kb(this.root):Ed;return this.ea?new ff(this.da,a,!1):a};f.I=function(){return this.l};f.X=function(){return this.i};f.F=function(){var a=this.o;return null!=a?a:this.o=a=hc(this)};f.m=function(a,b){return we(this,b)};f.Va=function(){return new hf({},this.root,this.i,this.ea,this.da)};f.R=function(){return ib(Gc,this.l)};
f.Ta=function(a,b,c){if(null==b)return this.ea&&c===this.da?this:new gf(this.l,this.ea?this.i:this.i+1,this.root,!0,c,null);a=new Ke;b=(null==this.root?Se:this.root).ja(0,Wb(b),b,c,a);return b===this.root?this:new gf(this.l,a.qa?this.i+1:this.i,b,this.ea,this.da,null)};f.P=function(){if(0<this.i){var a=null!=this.root?this.root.Xa():null;return this.ea?P(new U(null,2,5,Fd,[null,this.da],null),a):a}return null};f.L=function(a,b){return new gf(b,this.i,this.root,this.ea,this.da,this.o)};
f.N=function(a,b){if(Nc(b))return Xa(this,D.a(b,0),D.a(b,1));for(var c=this,d=H(b);;){if(null==d)return c;var e=J(d);if(Nc(e))c=Xa(c,D.a(e,0),D.a(e,1)),d=M(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.T(null,c);case 3:return this.H(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.T(null,c)};a.g=function(a,c,d){return this.H(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(Ha(b)))};f.b=function(a){return this.T(null,a)};f.a=function(a,b){return this.H(null,a,b)};var Gc=new gf(null,0,null,!1,null,ic);gf.prototype[Ga]=function(){return O(this)};
function hf(a,b,c,d,e){this.A=a;this.root=b;this.count=c;this.ea=d;this.da=e;this.h=258;this.v=56}function jf(a,b,c){if(a.A){if(null==b)a.da!==c&&(a.da=c),a.ea||(a.count+=1,a.ea=!0);else{var d=new Ke;b=(null==a.root?Se:a.root).ka(a.A,0,Wb(b),b,c,d);b!==a.root&&(a.root=b);d.qa&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=hf.prototype;f.X=function(){if(this.A)return this.count;throw Error("count after persistent!");};
f.T=function(a,b){return null==b?this.ea?this.da:null:null==this.root?null:this.root.Na(0,Wb(b),b)};f.H=function(a,b,c){return null==b?this.ea?this.da:c:null==this.root?c:this.root.Na(0,Wb(b),b,c)};
f.cb=function(a,b){var c;a:if(this.A)if(null!=b?b.h&2048||b.Gb||(b.h?0:u($a,b)):u($a,b))c=jf(this,He.b?He.b(b):He.call(null,b),Ie.b?Ie.b(b):Ie.call(null,b));else{c=H(b);for(var d=this;;){var e=J(c);if(t(e))c=M(c),d=jf(d,He.b?He.b(e):He.call(null,e),Ie.b?Ie.b(e):Ie.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");return c};f.eb=function(){var a;if(this.A)this.A=null,a=new gf(null,this.count,this.root,this.ea,this.da,null);else throw Error("persistent! called twice");return a};
f.Wa=function(a,b,c){return jf(this,b,c)};var Qd=function Qd(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Qd.s(0<c.length?new I(c.slice(0),0):null)};Qd.s=function(a){for(var b=H(a),c=xb(Gc);;)if(b){a=M(M(b));var d=J(b),b=J(M(b)),c=Ab(c,d,b),b=a}else return zb(c)};Qd.G=0;Qd.C=function(a){return Qd.s(H(a))};
var kf=function kf(b){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return kf.s(0<c.length?new I(c.slice(0),0):null)};kf.s=function(a){a=a instanceof I&&0===a.j?a.c:Ia(a);for(var b=[],c=0;;)if(c<a.length){var d=a[c],e=a[c+1];-1===ze(b,d)&&(b.push(d),b.push(e));c+=2}else break;return new ua(null,b.length/2,b,null)};kf.G=0;kf.C=function(a){return kf.s(H(a))};function lf(a,b){this.u=a;this.$=b;this.h=32374988;this.v=0}f=lf.prototype;f.toString=function(){return Mb(this)};
f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.$};f.aa=function(){var a=(null!=this.u?this.u.h&128||this.u.ab||(this.u.h?0:u(Ua,this.u)):u(Ua,this.u))?this.u.aa(null):M(this.u);return null==a?null:new lf(a,this.$)};f.F=function(){return fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.$)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return this.u.W(null).lb()};
f.ca=function(){var a=(null!=this.u?this.u.h&128||this.u.ab||(this.u.h?0:u(Ua,this.u)):u(Ua,this.u))?this.u.aa(null):M(this.u);return null!=a?new lf(a,this.$):L};f.P=function(){return this};f.L=function(a,b){return new lf(this.u,b)};f.N=function(a,b){return P(b,this)};lf.prototype[Ga]=function(){return O(this)};function Ce(a){return(a=H(a))?new lf(a,null):null}function He(a){return ab(a)}function mf(a,b){this.u=a;this.$=b;this.h=32374988;this.v=0}f=mf.prototype;f.toString=function(){return Mb(this)};
f.equiv=function(a){return this.m(null,a)};f.I=function(){return this.$};f.aa=function(){var a=(null!=this.u?this.u.h&128||this.u.ab||(this.u.h?0:u(Ua,this.u)):u(Ua,this.u))?this.u.aa(null):M(this.u);return null==a?null:new mf(a,this.$)};f.F=function(){return fc(this)};f.m=function(a,b){return uc(this,b)};f.R=function(){return xc(L,this.$)};f.U=function(a,b){return yc(b,this)};f.V=function(a,b,c){return Ac(b,c,this)};f.W=function(){return this.u.W(null).mb()};
f.ca=function(){var a=(null!=this.u?this.u.h&128||this.u.ab||(this.u.h?0:u(Ua,this.u)):u(Ua,this.u))?this.u.aa(null):M(this.u);return null!=a?new mf(a,this.$):L};f.P=function(){return this};f.L=function(a,b){return new mf(this.u,b)};f.N=function(a,b){return P(b,this)};mf.prototype[Ga]=function(){return O(this)};function De(a){return(a=H(a))?new mf(a,null):null}function Ie(a){return bb(a)}
function od(a){if(null!=a&&(a.v&4096||a.Ib))return a.name;if("string"===typeof a)return a;throw Error([B("Doesn't support name: "),B(a)].join(""));}function nf(a){a:for(var b=a;;)if(H(b))b=M(b);else break a;return a}
function of(a,b,c,d,e,g,h){var k=pa;pa=null==pa?null:pa-1;try{if(null!=pa&&0>pa)return G(a,"#");G(a,c);if(0===Aa.b(g))H(h)&&G(a,function(){var a=pf.b(g);return t(a)?a:"..."}());else{if(H(h)){var l=J(h);b.g?b.g(l,a,g):b.call(null,l,a,g)}for(var p=M(h),m=Aa.b(g)-1;;)if(!p||null!=m&&0===m){H(p)&&0===m&&(G(a,d),G(a,function(){var a=pf.b(g);return t(a)?a:"..."}()));break}else{G(a,d);var q=J(p);c=a;h=g;b.g?b.g(q,c,h):b.call(null,q,c,h);var r=M(p);c=m-1;p=r;m=c}}return G(a,e)}finally{pa=k}}
function qf(a,b){for(var c=H(b),d=null,e=0,g=0;;)if(g<e){var h=d.K(null,g);G(a,h);g+=1}else if(c=H(c))d=c,Oc(d)?(c=Fb(d),e=Gb(d),d=c,h=S(c),c=e,e=h):(h=J(d),G(a,h),c=M(d),d=null,e=0),g=0;else return null}var rf={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function sf(a){return[B('"'),B(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return rf[a]})),B('"')].join("")}
function tf(a,b){var c=Tc(bc(a,ya));return c?(c=null!=b?b.h&131072||b.Hb?!0:!1:!1)?null!=Jc(b):c:c}
function uf(a,b,c){if(null==a)return G(b,"nil");if(tf(c,a)){G(b,"^");var d=Jc(a);W.g?W.g(d,b,c):W.call(null,d,b,c);G(b," ")}if(a.vb)return a.Mb(b);if(null!=a&&(a.h&2147483648||a.O))return a.D(null,b,c);if(!0===a||!1===a||"number"===typeof a)return G(b,""+B(a));if(null!=a&&a.constructor===Object)return G(b,"#js "),d=V.a(function(b){return new U(null,2,5,Fd,[nd.b(b),a[b]],null)},Pc(a)),vf.S?vf.S(d,W,b,c):vf.call(null,d,W,b,c);if(Ba(a))return of(b,W,"#js ["," ","]",c,a);if("string"==typeof a)return t(wa.b(c))?
G(b,sf(a)):G(b,a);if("function"==n(a)){var e=a.name;c=t(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Function":e;return qf(b,wc(["#object[",c,' "',""+B(a),'"]'],0))}if(a instanceof Date)return c=function(a,b){for(var c=""+B(a);;)if(S(c)<b)c=[B("0"),B(c)].join("");else return c},qf(b,wc(['#inst "',""+B(a.getUTCFullYear()),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),
"-",'00:00"'],0));if(a instanceof RegExp)return qf(b,wc(['#"',a.source,'"'],0));if(null!=a&&(a.h&2147483648||a.O))return vb(a,b,c);if(t(a.constructor.fb))return qf(b,wc(["#object[",a.constructor.fb.replace(RegExp("/","g"),"."),"]"],0));e=a.constructor.name;c=t(function(){var a=null==e;return a?a:/^[\s\xa0]*$/.test(e)}())?"Object":e;return qf(b,wc(["#object[",c," ",""+B(a),"]"],0))}function W(a,b,c){var d=wf.b(c);return t(d)?(c=Fc.g(c,xf,uf),d.g?d.g(a,b,c):d.call(null,a,b,c)):uf(a,b,c)}
function Vd(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return yf(0<b.length?new I(b.slice(0),0):null)}function yf(a){var b=ta();if(null==a||Ca(H(a)))b="";else{var c=B,d=new fa;a:{var e=new Lb(d);W(J(a),e,b);a=H(M(a));for(var g=null,h=0,k=0;;)if(k<h){var l=g.K(null,k);G(e," ");W(l,e,b);k+=1}else if(a=H(a))g=a,Oc(g)?(a=Fb(g),h=Gb(g),g=a,l=S(a),a=h,h=l):(l=J(g),G(e," "),W(l,e,b),a=M(g),g=null,h=0),k=0;else break a}b=""+c(d)}return b}
function vf(a,b,c,d){return of(c,function(a,c,d){var k=ab(a);b.g?b.g(k,c,d):b.call(null,k,c,d);G(c," ");a=bb(a);return b.g?b.g(a,c,d):b.call(null,a,c,d)},"{",", ","}",d,H(a))}I.prototype.O=!0;I.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};pd.prototype.O=!0;pd.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};bf.prototype.O=!0;bf.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};Ae.prototype.O=!0;
Ae.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};me.prototype.O=!0;me.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};ld.prototype.O=!0;ld.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};tc.prototype.O=!0;tc.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};gf.prototype.O=!0;gf.prototype.D=function(a,b,c){return vf(this,W,b,c)};df.prototype.O=!0;df.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};qe.prototype.O=!0;
qe.prototype.D=function(a,b,c){return of(b,W,"["," ","]",c,this)};td.prototype.O=!0;td.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};Nd.prototype.O=!0;Nd.prototype.D=function(a,b,c){G(b,"#object [cljs.core.Atom ");W(new ua(null,1,[zf,this.state],null),b,c);return G(b,"]")};mf.prototype.O=!0;mf.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};U.prototype.O=!0;U.prototype.D=function(a,b,c){return of(b,W,"["," ","]",c,this)};id.prototype.O=!0;
id.prototype.D=function(a,b){return G(b,"()")};ua.prototype.O=!0;ua.prototype.D=function(a,b,c){return vf(this,W,b,c)};lf.prototype.O=!0;lf.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};hd.prototype.O=!0;hd.prototype.D=function(a,b,c){return of(b,W,"("," ",")",c,this)};Zb.prototype.Ua=!0;Zb.prototype.Qa=function(a,b){if(b instanceof Zb)return Yb(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};T.prototype.Ua=!0;
T.prototype.Qa=function(a,b){if(b instanceof T)return md(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};qe.prototype.Ua=!0;qe.prototype.Qa=function(a,b){if(Nc(b))return Vc(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};U.prototype.Ua=!0;U.prototype.Qa=function(a,b){if(Nc(b))return Vc(this,b);throw Error([B("Cannot compare "),B(this),B(" to "),B(b)].join(""));};function Af(){}
var Bf=function Bf(b){if(null!=b&&null!=b.Cb)return b.Cb(b);var c=Bf[n(null==b?null:b)];if(null!=c)return c.b?c.b(b):c.call(null,b);c=Bf._;if(null!=c)return c.b?c.b(b):c.call(null,b);throw x("IEncodeJS.-clj-\x3ejs",b);};function Cf(a){return(null!=a?a.Bb||(a.ub?0:u(Af,a)):u(Af,a))?Bf(a):"string"===typeof a||"number"===typeof a||a instanceof T||a instanceof Zb?Df.b?Df.b(a):Df.call(null,a):yf(wc([a],0))}
var Df=function Df(b){if(null==b)return null;if(null!=b?b.Bb||(b.ub?0:u(Af,b)):u(Af,b))return Bf(b);if(b instanceof T)return od(b);if(b instanceof Zb)return""+B(b);if(Mc(b)){var c={};b=H(b);for(var d=null,e=0,g=0;;)if(g<e){var h=d.K(null,g),k=Ec(h,0),h=Ec(h,1);c[Cf(k)]=Df(h);g+=1}else if(b=H(b))Oc(b)?(e=Fb(b),b=Gb(b),d=e,e=S(e)):(e=J(b),d=Ec(e,0),e=Ec(e,1),c[Cf(d)]=Df(e),b=M(b),d=null,e=0),g=0;else break;return c}if(Kc(b)){c=[];b=H(V.a(Df,b));d=null;for(g=e=0;;)if(g<e)k=d.K(null,g),c.push(k),g+=1;
else if(b=H(b))d=b,Oc(d)?(b=Fb(d),g=Gb(d),d=b,e=S(b),b=g):(b=J(d),c.push(b),b=M(d),d=null,e=0),g=0;else break;return c}return b};function Ef(){}var Ff=function Ff(b,c){if(null!=b&&null!=b.Ab)return b.Ab(b,c);var d=Ff[n(null==b?null:b)];if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);d=Ff._;if(null!=d)return d.a?d.a(b,c):d.call(null,b,c);throw x("IEncodeClojure.-js-\x3eclj",b);};
function Gf(a){var b=wc([new ua(null,1,[Hf,!1],null)],0),c=null!=b&&(b.h&64||b.La)?Cd(Qd,b):b,d=bc(c,Hf);return function(a,c,d,k){return function p(m){return(null!=m?m.Ub||(m.ub?0:u(Ef,m)):u(Ef,m))?Ff(m,Cd(kf,b)):Sc(m)?nf(V.a(p,m)):Kc(m)?Wd(null==m?null:Oa(m),V.a(p,m)):Ba(m)?le(V.a(p,m)):Ea(m)===Object?Wd(Kd,function(){return function(a,b,c,d){return function A(e){return new pd(null,function(a,b,c,d){return function(){for(;;){var a=H(e);if(a){if(Oc(a)){var b=Fb(a),c=S(b),g=new rd(Array(c),0);a:for(var h=
0;;)if(h<c){var k=D.a(b,h),k=new U(null,2,5,Fd,[d.b?d.b(k):d.call(null,k),p(m[k])],null);g.add(k);h+=1}else{b=!0;break a}return b?ud(g.ia(),A(Gb(a))):ud(g.ia(),null)}g=J(a);return P(new U(null,2,5,Fd,[d.b?d.b(g):d.call(null,g),p(m[g])],null),A(cc(a)))}return null}}}(a,b,c,d),null,null)}}(a,c,d,k)(Pc(m))}()):m}}(b,c,d,t(d)?nd:B)(a)}function Jf(a,b){return zd(Ka(function(b,d){var e=a.b?a.b(d):a.call(null,d),g=Q.a($b(b,e,Bc),d);return Ab(b,e,g)},xb(Kd),b))};var Kf=new T(null,"suit","suit",-869827520),Lf=new T(null,"spades","spades",1715303139),ya=new T(null,"meta","meta",1499536964),Mf=new T(null,"table","table",-564943036),za=new T(null,"dup","dup",556298533),Nf=new T(null,"diamonds","diamonds",-145346074),Ud=new Zb(null,"new-value","new-value",-1567397401,null),Rd=new T(null,"validator","validator",-1966190681),Of=new T(null,"rank","rank",-1706728502),Jd=new Zb(null,"meta9967","meta9967",-2062318516,null),zf=new T(null,"val","val",128701612),Td=new Zb(null,
"validate","validate",1439230700,null),xf=new T(null,"fallback-impl","fallback-impl",-1501286995),va=new T(null,"flush-on-newline","flush-on-newline",-151457939),wa=new T(null,"readably","readably",1129599760),pf=new T(null,"more-marker","more-marker",-14717935),Pf=new T(null,"clubs","clubs",-1540603567),Qf=new T(null,"hearts","hearts",-701365391),Aa=new T(null,"print-length","print-length",1931866356),Rf=new T(null,"pass","pass",1574159993),Id=new Zb(null,"quote","quote",1377916282,null),Hd=new T(null,
"arglists","arglists",1661989754),Gd=new Zb(null,"nil-iter","nil-iter",1101030523,null),wf=new T(null,"alt-impl","alt-impl",670969595),Sf=new T(null,"player-name","player-name",-823697956),Hf=new T(null,"keywordize-keys","keywordize-keys",1310784252);function Tf(a){return console.log.apply(console,Df(P("Vann:",a)))};function Uf(a){switch(J(jd(a))){case "\u2660":return Lf;case "\u2665":return Qf;case "\u2666":return Nf;case "\u2663":return Pf;default:throw Error([B("No matching clause: "),B(J(jd(a)))].join(""));}}function Vf(a){switch(a){case "J":return 11;case "Q":return 12;case "K":return 13;case "A":return 14;default:throw Error([B("No matching clause: "),B(a)].join(""));}}
function Wf(a){var b;b=B;var c;a:{c=Bc;for(var d=a;;)if(M(d))c=Q.a(c,J(d)),d=M(d);else{c=H(c);break a}}b=Cd(b,c);c=parseInt(b);c=t(isNaN(c))?null:c;b=null==c?Vf(b):c;return new ua(null,2,[Of,b,Kf,Uf(a)],null)};function Xf(){return function(a){return N.a(2,S(a))}}function Yf(a){return Md(function(a){return N.a(14,a)},a)}function Zf(a){return Dd(ed,0,V.a(S,De(Jf(Of,a))))}function $f(a){return Wd(V.a(Wf,bc(a,"Hand")),V.a(Wf,bc(a,"Tisch")))}function ag(a,b,c){return Ld(function(a){return Dd(b,a,c)},V.a(Of,a))}function bg(a){return Md(function(a){return 5<=S(a)},De(Jf(Kf,a)))}
function cg(a){a=bc(a,"Rundenname");if(t(N.a?N.a("preflop",a):N.call(null,"preflop",a)))return 7;if(t(N.a?N.a("flop",a):N.call(null,"flop",a)))return 13;if(t(N.a?N.a("turncard",a):N.call(null,"turncard",a)))return 15;if(t(N.a?N.a("river",a):N.call(null,"river",a)))return 16;if(t(N.a?N.a("showdown",a):N.call(null,"showdown",a)))return 17;throw Error([B("No matching clause: "),B(a)].join(""));}
function dg(a){var b=Gf(a);a=V.a(Wf,bc(b,"Hand"));var c=$f(b),d=V.a(Wf,bc(b,"Tisch"));bc(b,"Rundenname");var e=cg(b);Zf(a);var d=Zf(d),g=Zf(c);if(t(Md(Xf(),De(Jf(Of,a)))))a="rraise";else if(2<=g&&g>d)a="rraise";else if(t(bg($f(b))))a="rraise";else{b=V.a(Of,c);b=t(Yf(b))?P(1,b):b;a:for(b=Yc(b),c=new U(null,1,5,Fd,[J(b)],null),d=Bc;;)if(1<S(b))if(N.a(J(b)+1,J(M(b))))g=cc(b),c=Q.a(c,J(M(b))),b=g;else var g=cc(b),h=new U(null,1,5,Fd,[J(M(b))],null),d=Q.a(d,c),b=g,c=h;else{b=Q.a(d,c);break a}b=V.a(S,b);
a:for(b=Yc(b);;)if(c=M(b),null!=c)b=c;else{b=J(b);break a}a=t(5<=b)?"rraise":t(ag(a,dd,wc([13],0)))?"rraise":t(ag(a,cd,wc([6],0)))?"rfold":$c(bd,V.a(Of,a))<e?"rfold":"rcheck"}return a}ba("bpeter.vann.game.play",dg);var eg=Pd?Pd(null):Od.call(null,null),fg,gg=new ua(null,3,[Mf,null,Sf,null,Rf,null],null);fg=Pd?Pd(gg):Od.call(null,gg);function hg(a){return(jc.b?jc.b(eg):jc.call(null,eg)).send(a)}function ig(a){a=window.JSON.parse(a.substring(1));a=Gf(a);return hg(dg(a))}function jg(a){return t(N.a(a,"o"))?(Tf(wc(["signed up successfully"],0)),Sd.a?Sd.a(kg,ig):Sd.call(null,kg,ig)):Tf(wc(["negative sign-up response:",a.substring(1)],0))}var kg=Pd?Pd(jg):Od.call(null,jg);
function lg(){nf(V.a(function(a){return(jc.b?jc.b(eg):jc.call(null,eg))[J(a)]=J(M(a))},new U(null,4,5,Fd,[new U(null,2,5,Fd,["onopen",function(){Tf(wc(["socket open"],0));var a=jc.b?jc.b(fg):jc.call(null,fg);Tf(wc(["signing up"],0));a=[B("p"),B(Mf.b(a)),B("\n"),B(Sf.b(a)),B("\n"),B(Rf.b(a))].join("");return hg(a)}],null),new U(null,2,5,Fd,["onclose",function(){return Tf(wc(["socket closed"],0))}],null),new U(null,2,5,Fd,["onerror",function(a){return Tf(wc([[B("socket error"),B(a)].join("")],0))}],
null),new U(null,2,5,Fd,["onmessage",function(a){return(jc.b?jc.b(kg):jc.call(null,kg)).call(null,a.data)}],null)],null)));window.addEventListener("unload",function(){(jc.b?jc.b(eg):jc.call(null,eg)).close();var a=jc.b?jc.b(eg):jc.call(null,eg);return Sd.a?Sd.a(a,null):Sd.call(null,a,null)});return Tf(wc(["websocket initialized"],0))}
ba("bpeter.vann.core.main",function(a,b,c,d){Tf(wc(["starting to play:",[B(a),B(" "),B(b),B(" "),B(c),B(" "),B(d)].join("")],0));b=new ua(null,3,[Mf,b,Sf,c,Rf,d],null);Sd.a?Sd.a(fg,b):Sd.call(null,fg,b);a=new WebSocket(a);Sd.a?Sd.a(eg,a):Sd.call(null,eg,a);return lg()});
})();

//# sourceMappingURL=vann.js.map